[package]
name = "fedimint-wallet-tests"
version = "0.2.1-rc4"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-wallet-tests contains integration tests for the lightning module"
license = "MIT"
publish = false

[[test]]
name = "fedimint_wallet_tests"
path = "tests/tests.rs"

[dependencies]
anyhow = "1.0.66"
assert_matches = "1.5.0"
async-trait = "0.1.73"
bitcoin = "0.29.2"
erased-serde = "0.3"
fedimint-bitcoind = { path = "../../fedimint-bitcoind" }
fedimint-client = { path = "../../fedimint-client" }
fedimint-core ={ path = "../../fedimint-core" }
fedimint-dummy-client = { path = "../fedimint-dummy-client" }
fedimint-dummy-common = { path = "../fedimint-dummy-common" }
fedimint-dummy-server = { path = "../fedimint-dummy-server" }
fedimint-logging = { path = "../../fedimint-logging" }
fedimint-server = { path = "../../fedimint-server" }
fedimint-testing ={ path = "../../fedimint-testing" }
fedimint-wallet-client = { path = "../fedimint-wallet-client" }
fedimint-wallet-common = { path = "../fedimint-wallet-common" }
fedimint-wallet-server = { path = "../fedimint-wallet-server" }
futures = "0.3.28"
miniscript = { version = "9.0.2" }
tokio = { version = "1.26.0", features = ["sync"] }
tracing = "0.1.37"
