[package]
authors = { workspace = true }
description = "fedimint-wallet-tests contains integration tests for the lightning module"
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-wallet-tests"
publish = false
version = { workspace = true }

[[bin]]
name = "wallet-module-tests"
path = "src/bin/wallet-module-tests.rs"

[[test]]
name = "fedimint_wallet_tests"
path = "tests/tests.rs"

[dependencies]
anyhow = { workspace = true }
bitcoin = { workspace = true }
bitcoincore-rpc = { workspace = true }
clap = { workspace = true }
devimint = { workspace = true }
devimintd-client = { workspace = true }
fedimint-api-client = { workspace = true }
fedimint-client = { workspace = true }
fedimint-client-module = { workspace = true }
fedimint-connectors = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-server = { workspace = true }
fedimint-server-core = { workspace = true }
fedimint-testing = { workspace = true }
fedimint-testing-core = { workspace = true }
fedimint-wallet-client = { workspace = true }
fedimint-wallet-common = { workspace = true }
fedimint-wallet-server = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
fedimint-dummy-client = { workspace = true }
fedimint-dummy-common = { workspace = true }
fedimint-dummy-server = { workspace = true }

[lints]
workspace = true
