[package]
name = "fedimint-wallet-tests"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "fedimint-wallet-tests contains integration tests for the lightning module"
license = { workspace = true }
publish = false

[[bin]]
name = "circular-deposit-test"
path = "src/bin/circular-deposit-test.rs"

[[test]]
name = "fedimint_wallet_tests"
path = "tests/tests.rs"

[dependencies]
anyhow = { workspace = true }
bitcoin = { workspace = true }
bitcoincore-rpc = { workspace = true }
devimint = { workspace = true }
fedimint-api-client = { workspace = true }
fedimint-client = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-server = { workspace = true }
fedimint-testing = { workspace = true }
fedimint-wallet-client = { workspace = true }
fedimint-wallet-common = { workspace = true }
fedimint-wallet-server = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
fedimint-dummy-client = { workspace = true }
fedimint-dummy-common = { workspace = true }
fedimint-dummy-server = { workspace = true }
