[package]
name = "fedimint-gateway-client"
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
readme = { workspace = true }
description = "Client for interacting with the gateway"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[features]
default = ["tor"]
tor = ["fedimint-gateway-common/tor"]

[[bin]]
name = "gateway-cli"
path = "src/main.rs"

[lib]
name = "fedimint_gateway_client"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
bcrypt = { workspace = true }
bitcoin = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
clap_complete = "4.5.47"
fedimint-core = { workspace = true }
fedimint-eventlog = { workspace = true }
fedimint-gateway-common = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-mint-client = { workspace = true }
lightning-invoice = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[build-dependencies]
fedimint-build = { workspace = true }
