[package]
name = "fedimint-wasm-tests"
version = "0.0.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = [ "rlib", "cdylib" ]

[dependencies]
anyhow = "1.0.69"
futures = "0.3.26"
ring = { version = "0.17.5", features = ["wasm32_unknown_unknown_js"] }
fedimint-client = { path = "../fedimint-client" }
fedimint-core = { path = "../fedimint-core" }
fedimint-mint-client = { path = "../modules/fedimint-mint-client" }
fedimint-mint-common = { path = "../modules/fedimint-mint-common" }
fedimint-ln-client = { path = "../modules/fedimint-ln-client" }
fedimint-wallet-client = { path = "../modules/fedimint-wallet-client" }
js-sys = "0.3.61"
wasm-bindgen = "=0.2.87" # must match the nix provided wasm-bindgen-cli version
wasm-bindgen-futures = "0.4.34"
wasm-bindgen-test = "0.3.34"
gloo-net = "0.2.6"
rand = "0.8.5"
