[package]
name = "fedimint-wasm-tests"
version = "0.3.4-rc.0"
edition = "2021"
license = "MIT"
description = "Wasm tests for the fedimint."
publish = false

[lib]
crate-type = [ "rlib", "cdylib" ]
name = "fedimint_wasm_tests"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.81"
futures = "0.3.30"
ring = { version = "0.17.8", features = ["wasm32_unknown_unknown_js"] }
fedimint-client = { path = "../fedimint-client" }
fedimint-core = { path = "../fedimint-core" }
fedimint-mint-client = { path = "../modules/fedimint-mint-client" }
fedimint-mint-common = { path = "../modules/fedimint-mint-common" }
fedimint-ln-common = { path = "../modules/fedimint-ln-common" }
fedimint-ln-client = { path = "../modules/fedimint-ln-client" }
fedimint-wallet-client = { path = "../modules/fedimint-wallet-client" }
js-sys = "0.3.69"
wasm-bindgen = "=0.2.92" # must match the nix provided wasm-bindgen-cli version
wasm-bindgen-futures = "0.4.42"
wasm-bindgen-test = "0.3.42"
gloo-net = "0.2.6"
rand = "0.8.5"
