[package]
description = "Wasm tests for the fedimint."
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-wasm-tests"
publish = false
version = { workspace = true }

[package.metadata.cargo-udeps.ignore]
normal = ["fedimint-cursed-redb"]

[lib]
crate-type = ["rlib", "cdylib"]
name = "fedimint_wasm_tests"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
fedimint-client = { workspace = true }
fedimint-connectors = { workspace = true }
fedimint-core = { workspace = true }
# currently unused, only to test compilation
fedimint-cursed-redb = { workspace = true }
fedimint-derive-secret = { workspace = true }
fedimint-ln-client = { workspace = true }
fedimint-ln-common = { workspace = true }
fedimint-mint-client = { workspace = true }
fedimint-wallet-client = { workspace = true }
futures = { workspace = true }
gloo-net = { workspace = true }
rand = { workspace = true }
wasm-bindgen-test = { workspace = true }
# workaround https://github.com/n0-computer/iroh/issues/3252
web-sys = { workspace = true }

[lints]
workspace = true
