[package]
name = "fedimint-wasm-tests"
version = { workspace = true }
edition = "2021"
license = "MIT"
description = "Wasm tests for the fedimint."
publish = false

[lib]
crate-type = ["rlib", "cdylib"]
name = "fedimint_wasm_tests"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
fedimint-api-client = { workspace = true }
fedimint-client = { workspace = true }
fedimint-core = { workspace = true }
fedimint-ln-client = { workspace = true }
fedimint-ln-common = { workspace = true }
fedimint-mint-client = { workspace = true }
fedimint-wallet-client = { workspace = true }
futures = { workspace = true }
gloo-net = "0.6.0"
rand = { workspace = true }
wasm-bindgen-test = "0.3.42"
