[package]
name = "clientd"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "clientd is the root client process for client-lib subprocesses to send/receive transactions."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "clientd"
path = "src/lib.rs"

[[bin]]
name = "clientd-cli"
path = "src/bin/clientd-cli.rs"

[[bin]]
name = "clientd"
path = "src/main.rs"

[dependencies]
mint-client = { path = "../client-lib" }
fedimint-api = { path = "../../fedimint-api" }
fedimint-core = { path = "../../fedimint-core" }
fedimint-rocksdb = { path = "../../fedimint-rocksdb" }
anyhow = "1.0.65"
async-trait = "0.1.57"
bitcoin = { version = "0.29.1", features = [ "serde" ] }
bitcoin_hashes = "0.11.0"
reqwest = { version = "0.11.12", features = [ "json" ], default-features = false }
tokio = { version = "1.21.2", features = ["full"] }
serde = { version = "1.0.145", features = [ "derive" ] }
serde_json = "1.0.86"
tracing ="0.1.37"
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
clap = { version = "4.0.9", features = ["derive"] }
axum = "0.5.16"
tower = "0.4.13"
tower-http = { version = "0.3.4", features = [ "trace" ] }
rand = "0.8"
thiserror = "1.0.37"

[build-dependencies]
fedimint-build = { path = "../../fedimint-build" }
