[package]
name = "clientd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "clientd"
path = "src/lib.rs"

[[bin]]
name = "clientd-cli"
path = "src/bin/clientd-cli.rs"

[[bin]]
name = "clientd"
path = "src/main.rs"

[dependencies]
mint-client = { path = "../client-lib" }
fedimint-api = { path = "../../fedimint-api", features = [ "rocksdb" ] }
fedimint-core = { path = "../../fedimint-core" }
rocksdb = "0.19.0"
anyhow = "1.0.58"
bitcoin = { version = "0.28.1", features = [ "serde" ] }
bitcoin_hashes = "0.10.0"
sled = "0.34.6"
reqwest = { version = "0.11.0", features = [ "json" ], default-features = false }
tokio = { version = "1.19.2", features = ["full"] }
serde = { version = "1.0.118", features = [ "derive" ] }
serde_json = "1.0.82"
tracing ="0.1.22"
tracing-subscriber = { version = "0.3.1", features = [ "env-filter" ] }
clap = { version = "3.1.18", features = ["derive"] }
axum = "0.5.13"
tower = "0.4.13"
tower-http = { version = "0.3.4", features = [ "trace" ] }
rand = "0.6.5"
