[package]
name = "gateway-tests"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "gateway-tests contain integration tests for the gateway"
license = { workspace = true }
publish = false

# workaround: cargo-deny in Nix needs to see at least one
# artifact here
[[bin]]
name = "gateway-tests"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
devimint = { workspace = true }
fedimint-core = { workspace = true }
fedimint-gateway-server = { workspace = true }
fedimint-testing = { workspace = true }
itertools = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
