[package]
name = "ln-gateway"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "ln-gateway is a core lightning plugin which allows a Lightning node operator to receive or pay Lightning invoices on behalf of fedimint users."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ln_gateway"
path = "src/lib.rs"

[[bin]]
name = "ln_gateway"
path = "src/bin/ln_gateway.rs"

[dependencies]
async-trait = "0.1.52"
axum = "0.5.15"
bitcoin_hashes = "0.10.0"
bitcoin = { version = "0.28.1", features = ["serde", "use-serde"] }
cln-rpc = "0.1"
cln-plugin = "0.1"
futures = "0.3.21"
hex = "0.4.3"
lightning-invoice = "0.18.0"
fedimint = { path = "../fedimint/" }
fedimint-api = { path = "../fedimint-api", features = ["rocksdb"] }
mint-client = { path = "../client/client-lib" }
rand = "0.6"
rocksdb = "0.19.0"
secp256k1 = "0.22.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.61"
sled = "0.34.6"
thiserror = "1.0.30"
tracing = { version = "0.1.26", default-features = false, features= ["log", "attributes", "std"] }
tokio = {version = "1.21", features = ["full"]}
tower-http = { version = "0.3.4", features = ["cors"] }
url = { version = "2.2.2", features = ["serde"] }
