[package]
authors = { workspace = true }
description = "fedimint-redb provides a direct redb database implementation for Fedimint server."
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-redb"
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_redb"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }

futures = { workspace = true }
redb = "2.6.0"
tracing = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
fedimint-db-locked = { workspace = true }

[target.'cfg(target_family = "wasm")'.dependencies]
gloo-utils = "0.2"
web-sys = { version = "0.3", features = [
    "FileSystemSyncAccessHandle",
    "FileSystemReadWriteOptions",
] }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "time",
    "macros",
] }

[lints]
workspace = true
