[package]
name = "fedimint-unknown-server"
version = "0.3.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-dummy is a test fedimint module that doesn't have any client side implementation."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_unknown_server"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.73"
erased-serde = "0.3"
futures = "0.3"
fedimint-core = { version = "0.3.0-alpha", path = "../../fedimint-core" }
fedimint-unknown-common = { version = "0.3.0-alpha", path = "../fedimint-unknown-common" }
rand = "0.8"
serde = { version = "1.0.149", features = [ "derive" ] }
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0.39"
tracing = "0.1.37"
tokio = { version = "1.26.0", features = ["sync"] }
