[package]
name = "fedimint-unknown-server"
version = "0.4.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-unknown-server is a test fedimint module that doesn't have any client side implementation."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_unknown_server"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
erased-serde = { workspace = true }
fedimint-core = { workspace = true }
fedimint-unknown-common = { version = "=0.4.0-alpha", path = "../fedimint-unknown-common" }
strum = { workspace = true }
strum_macros = { workspace = true }
