[package]
name = "fedimint-unknown-server"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "fedimint-unknown-server is a test fedimint module that doesn't have any client side implementation."
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_unknown_server"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
erased-serde = { workspace = true }
fedimint-core = { workspace = true }
fedimint-server-core = { workspace = true }
fedimint-unknown-common = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
