[package]
name = "fedimint-portalloc"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "Port allocation utility for Fedimint"
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_portalloc"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
dirs = "5.0.1"
fedimint-core = { workspace = true }
fs2 = "0.4.3"
rand = { workspace = true }
serde = { workspace = true }
serde_json = { version = "1.0.118", features = ["preserve_order"] }
tracing = { workspace = true }
