[package]
name = "fedimint-portalloc"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "Port allocation utility for Fedimint"
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_portalloc"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
dirs = { workspace = true }
fedimint-core = { workspace = true }
fs2 = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
