[package]
name = "fedimint-portalloc"
version = "0.3.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "Port allocation utility for Fedimint"
license = "MIT"

[lib]
name = "fedimint_portalloc"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.65"
fs2 = "0.4.3"
serde = { version = "1.0.149", features = [ "derive" ] }
serde_json = { version = "1.0.91", features = ["preserve_order"] }
tracing = "0.1.37"
rand = "0.8"
dirs = "5.0.1"
fedimint-core = { version = "0.2.0-rc2", path = "../../fedimint-core" }
