[default.extend-words]
substituters = "substituters"
# trips on some base64 string in the test
wel = "wel"
# common mistake that typos doesn't detect automatically
reasponse= "response"
# useful for "in/out" in the code
inout="inout"
# multi-user-chat
muc="muc"

# short for "backup"
bck="bck"

# metric id that typos doesn't like
"Fo"="Fo"

[files]
extend-exclude = [
  "db/**",
  "hfuzz_target/**",
  "hfuzz_workspace/**",
  "releases/**",
]
