[package]
name = "minimint-api"
version = "0.1.0"
authors = ["elsirion <elsirion@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
bitcoin = { version = "0.27.0", features = [ "rand", "serde" ] }
bitcoin_hashes = { version = "0.10", features = ["serde"] }
hex = "0.4.3"
minimint-derive = { path = "../minimint-derive" }
rand = "0.6.0"
secp256k1-zkp = { git = "https://github.com/elsirion/rust-secp256k1-zkp", branch = "minimint", features = [ "use-serde", "bitcoin_hashes", "global-context" ] }
serde = { version = "1.0.118", features = [ "derive" ] }
sled = "0.34"
tbs = { path = "../crypto/tbs"}
thiserror = "1.0.23"
tracing ="0.1.22"

[dev-dependencies]
tempdir = "0.3.7"