[package]
name = "minimint-api"
version = "0.1.0"
authors = ["elsirion <elsirion@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.58"
async-trait = "0.1"
bitcoin = { version = "0.28.1", features = [ "rand", "serde" ] }
bitcoin_hashes = { version = "0.10", features = ["serde"] }
futures = "0.3.21"
hex = "0.4.3"
lightning-invoice = "0.17.0"
minimint-derive = { path = "../minimint-derive" }
rand = "0.6.0"
secp256k1-zkp = { version = "0.6.0", features = [ "use-serde", "bitcoin_hashes", "global-context" ] }
serde = { version = "1.0.118", features = [ "derive" ] }
serde_json = "1.0.79"
sled = "0.34"
tbs = { path = "../crypto/tbs"}
thiserror = "1.0.23"
tracing ="0.1.22"

[target.'cfg(target_family="wasm")'.dependencies]
async-lock = "2.5"
# getrandom is transitive dependency of rand
# on wasm, we need to enable the js backend
# see https://docs.rs/getrandom/latest/getrandom/#indirect-dependencies and https://docs.rs/getrandom/latest/getrandom/#webassembly-support
getrandom = { version = "0.2.0", features = [ "js" ] }
gloo-timers = { version = "0.2.4", features = ["futures"] }
wasm-bindgen-futures = "0.4.31"

[target.'cfg(not(target_family="wasm"))'.dependencies]
tokio = { version = "1.19.2", features = ["rt", "rt-multi-thread", "sync", "time"] }

[dev-dependencies]
tempfile = "3.3.0"
test-log = { version = "0.2", features = [ "trace" ], default-features = false }
tracing-subscriber = { version = "0.3.1", features = [ "env-filter" ] }
