[package]
name = "fedimint-meta-tests"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-mint-tests contains integration tests for the meta module"
license = "MIT"
publish = false

# workaround: cargo-deny in Nix needs to see at least one
# artifact here
[[bin]]
name = "meta-sanity-test"
path = "src/bin/meta-sanity-test.rs"

[dependencies]
anyhow = { workspace = true }
devimint = { workspace = true }
fedimint-core = { workspace = true }
semver = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
