[package]
name = "fedimint-mint-common"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-mint is a chaumian ecash mint module."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fedimint_mint_common"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
bitcoin_hashes = { workspace = true }
fedimint-core = { workspace = true }
secp256k1-zkp = "0.9.2"
serde = { workspace = true }
tbs = { package = "fedimint-tbs", version = "=0.4.1", path = "../../crypto/tbs" }
thiserror = { workspace = true }
tracing = { workspace = true }
