[package]
name = "fedimint-mint-common"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "fedimint-mint-common is a chaumian ecash mint module. (common types)"
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_mint_common"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
bitcoin_hashes = { workspace = true }
fedimint-core = { workspace = true }
serde = { workspace = true }
tbs = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
