[package]
name = "minimint-mint"
version = "0.1.0"
authors = ["elsirion <elsirion@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
counter = "0.5.2"
itertools = "0.10.0"
minimint-api = { path = "../../minimint-api" }
minimint-derive = { path = "../../minimint-derive" }
rand = "0.6"
rayon = "1.5.0"
serde = { version = "1.0.118", features = [ "derive" ] }
tbs = { path = "../../crypto/tbs" }
thiserror = "1.0.23"
tracing ="0.1.22"

[dev-dependencies]
rand = "0.6.5"
