[package]
name = "fedimint"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint is the main consensus code for processing transactions and REST API"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
telemetry = ["opentelemetry", "opentelemetry-jaeger", "tracing-opentelemetry"]

[lib]
name = "fedimint"
path = "src/lib.rs"

[[bin]]
name = "fedimintd"
path = "src/bin/fedimintd.rs"

[[bin]]
name = "configgen"
path  = "src/bin/configgen.rs"

[dependencies]
anyhow = "1.0.58"
async-trait = "0.1.42"
bincode = "1.3.1"
bitcoin = "0.28.1"
bytes = "1.1.0"
clap = { version = "3.1.18", features = ["derive"] }
futures = "0.3.9"
hbbft = { git = "https://github.com/fedimint/hbbft" }
hex = "0.4.2"
itertools = "0.10.0"
jsonrpsee = { version = "0.14.0", features = ["ws-server"] }
mint-client = { path = "../client/client-lib" }
fedimint-api = { path = "../fedimint-api", features = ["rocksdb"] }
fedimint-core = { path = "../fedimint-core" }
fedimint-derive = { path = "../fedimint-derive" }
fedimint-wallet = { path = "../modules/fedimint-wallet", features = ["native"] }
opentelemetry = { version = "0.17.0", optional = true }
opentelemetry-jaeger = { version = "0.16.0", optional = true }
rand = "0.6.5"
rayon = "1.5.0"
rcgen = "0.9.2"
secp256k1-zkp = { version = "0.6.0", features = [ "global-context", "bitcoin_hashes" ] }
rocksdb = "0.19.0"
serde = { version = "1.0.118", features = [ "derive" ] }
serde_json = "1.0.61"
sha3 = "0.10.4"
sled = "0.34.6"
tbs = { path = "../crypto/tbs" }
thiserror = "1.0.23"
tokio = { version = "1.21.0", features = ["full"] }
tokio-rustls = "0.23.4"
tokio-util = { version = "0.7.3", features = [ "codec" ] }
tracing ="0.1.22"
tracing-subscriber = { version = "0.3.1", features = [ "env-filter" ] }
tracing-opentelemetry = { version = "0.17.2", optional = true}
threshold_crypto = { git = "https://github.com/fedimint/threshold_crypto" }
url = { version = "2.2.2", features = ["serde"] }
