[package]
name = "fedimint-mint-server"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-mint is a chaumian ecash mint module."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fedimint_mint_server"
path = "src/lib.rs"

[dependencies]
async-trait = "*"
fedimint-core-server = { path = "../../core/server" }
fedimint-api = { path = "../../fedimint-api" }
fedimint-mint-common = { path = "../mint-common/" }
tracing ="0.1.37"
