[package]
name = "fedimint-lnv2-common"
version = "0.4.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-ln is a lightning payment service module."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.cargo-udeps.ignore]
# cargo udeps can't detect that one
normal = ["aquamarine"]

[lib]
name = "fedimint_lnv2_common"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.82"
async-trait = "0.1.80"
aquamarine = "0.5.0"
bincode = "1"
bitcoin_hashes = { workspace = true }
bitcoin = { workspace = true }
erased-serde = { workspace = true }
futures = "0.3.24"
itertools = "0.12.1"
lightning-invoice = { version = "0.30.0", features = [ "serde" ] }
fedimint-client = { path = "../../fedimint-client" }
fedimint-core ={ path = "../../fedimint-core" }
secp256k1 = { version="0.27.0", default-features=false }
serde = { workspace = true }
serde_json = "1.0.116"
strum = "0.26"
strum_macros = "0.26"
thiserror = "1.0.59"
threshold_crypto = { workspace = true }
tracing = "0.1.37"
rand = "0.8"
url = { version = "2.3.1", features = ["serde"] }
# crypto deps
bls12_381 = { workspace = true }
ff = "0.13.0"
group = "0.13.0"
rand_chacha = "0.3.1"
tpe = { package = "fedimint-tpe", version = "=0.4.0-alpha", path = "../../crypto/tpe" }

[dev-dependencies]
tokio = {version = "1.37.0", features = [ "full" ] }
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
