[package]
authors = { workspace = true }
description = "fedimint-ln-common is a lightning payment service module (common types)."
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-lnv2-common"
version = { workspace = true }

[package.metadata.cargo-udeps.ignore]
# cargo udeps can't detect that one
normal = ["aquamarine"]

[lib]
name = "fedimint_lnv2_common"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bitcoin = { workspace = true }
fedimint-connectors = { workspace = true }
fedimint-core = { workspace = true }
fedimint-ln-common = { workspace = true }
group = { workspace = true }
lightning-invoice = { workspace = true }
lnurl-rs = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tpe = { workspace = true }

[lints]
workspace = true
