[package]
name = "fedimint-wallet-server"
version = "0.2.1-rc1"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-wallet is a n on-chain bitcoin wallet module. It uses a key-value store and is not a standard HD wallet."
license = "MIT"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_wallet_server"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1"
bitcoin = { version = "0.29.2", features = [ "rand", "serde"] }
erased-serde = "0.3"
fedimint-core = { version = "0.2.1-rc1", path = "../../fedimint-core" }
fedimint-wallet-common = { version = "0.2.1-rc1", path = "../fedimint-wallet-common" }
fedimint-bitcoind = { version = "0.2.1-rc1", path = "../../fedimint-bitcoind" }
futures = "0.3"
miniscript = { version = "9.0.2", features = [ "compiler", "serde" ] }
impl-tools = "0.8.0"
rand = "0.8"
secp256k1 = { version = "0.24.2", features = [ "serde" ] }
serde = { version = "1.0.149", features = [ "derive" ] }
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0.39"
tokio = { version = "1.26.0", features = ["sync"], optional = true }
tracing ="0.1.37"
url = "2.3.1"
validator = { version = "0.16", features = ["derive"] }
fedimint-server = { version = "0.2.1-rc1", path = "../../fedimint-server" }

[dev-dependencies]
fedimint-testing = { path = "../../fedimint-testing" }
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
tokio = { version = "1.26.0", features = ["full"] }
