[package]
name = "fedimint-wallet-server"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-wallet is a n on-chain bitcoin wallet module. It uses a key-value store and is not a standard HD wallet."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_wallet_server"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = "0.1"
bitcoin = { workspace = true }
erased-serde = { workspace = true }
fedimint-bitcoind = { version = "=0.4.3-rc.2", path = "../../fedimint-bitcoind" }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-metrics = { version = "=0.4.3-rc.2", path = "../../fedimint-metrics" }
fedimint-server = { version = "=0.4.3-rc.2", path = "../../fedimint-server" }
fedimint-wallet-common = { version = "=0.4.3-rc.2", path = "../fedimint-wallet-common" }
futures = { workspace = true }
hex = { workspace = true }
miniscript = { version = "10.0.0", features = [ "compiler", "serde" ] }
once_cell = { workspace = true }
rand = { workspace = true }
secp256k1 = { version = "0.27.0", features = [ "serde" ] }
serde = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tokio = { version = "1.38.0", features = ["sync"] }
tracing = { workspace = true }
