[package]
name = "fedimint-core-api"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-module provides common code used by both client and server. Can't be in fedimint-api because it depends on modules."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fedimint_core_api"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1.57"
bitcoin = "0.29.1"
anyhow = "1.0.65"
futures = "0.3.24"
fedimint-api = { path = "../../fedimint-api" }
thiserror = "1.0.23"
