[package]
name = "fedimint-tpe"
version = "0.4.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "tpe is a helper cryptography library for threshold point encryption"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
unstable = []

[lib]
name = "tpe"
path = "src/lib.rs"

[dependencies]
fedimint-core  = { version = "0.4.0-alpha", path = "../../fedimint-core/" }
bls12_381 = { version = "0.7.1", features = [ "zeroize", "groups" ] }
ff = "0.12.1"
group = "0.12.1"
rand = "0.8"
rand_chacha = "0.3.1"
bitcoin_hashes = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde-big-array = "0.5.1"
