[package]
authors = ["The Fedimint Developers"]
description = "fedimint walletv2 is an on-chain bitcoin wallet module. It uses a key-value store and is not a standard HD wallet. (server)"
edition = "2021"
license = "MIT"
name = "fedimint-walletv2-server"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"
version = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_walletv2_server"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bitcoin = { workspace = true }
erased-serde = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-server-core = { workspace = true }
fedimint-walletv2-common = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
miniscript = { workspace = true }
rand = { workspace = true }
secp256k1 = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
