[package]
name = "fedimint-lnv2-server"
version = "0.4.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-ln is a lightning payment service module."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fedimint_lnv2_server"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.85"
async-trait = "0.1.80"
erased-serde = { workspace = true }
futures = "0.3.24"
fedimint-bitcoind = { path = "../../fedimint-bitcoind" }
fedimint-core ={ path = "../../fedimint-core" }
fedimint-lnv2-common = { path = "../fedimint-lnv2-common" }
serde = { workspace = true }
strum = "0.26"
strum_macros = "0.26"
tpe = { package = "fedimint-tpe", version = "=0.4.0-alpha", path = "../../crypto/tpe" }
group = { workspace = true }
rand = { workspace = true }
fedimint-server = { path = "../../fedimint-server" }
bls12_381 = { workspace = true }
