[package]
name = "fedimint-lnv2-server"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "fedimint-ln is a lightning payment service module."
license = { workspace = true }

[lib]
name = "fedimint_lnv2_server"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bls12_381 = { workspace = true }
erased-serde = { workspace = true }
fedimint-core = { workspace = true }
fedimint-lnv2-common = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-server-core = { workspace = true }
futures = { workspace = true }
group = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tokio = { workspace = true }
tpe = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
