[package]
name = "fedimint-lnv2-server"
version = "0.4.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-ln is a lightning payment service module."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fedimint_lnv2_server"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.73"
bincode = "1"
bitcoin_hashes = "0.11.0"
erased-serde = { workspace = true }
futures = "0.3.24"
itertools = "0.10.5"
lightning-invoice = { version = "0.26.0", features = [ "serde" ] }
fedimint-bitcoind = { path = "../../fedimint-bitcoind" }
fedimint-core ={ path = "../../fedimint-core" }
fedimint-lnv2-common = { path = "../fedimint-lnv2-common" }
secp256k1 = { version="0.24.2", default-features=false }
serde = {version = "1.0.149", features = [ "derive" ] }
serde_json = "1.0.91"
strum = "0.24"
strum_macros = "0.24"
tpe = { package = "fedimint-tpe", version = "0.4.0-alpha", path = "../../crypto/tpe" }
thiserror = "1.0.39"
group = "0.12.1"
threshold_crypto = { workspace = true }
tokio = { version = "1.26", features = ["full"] }
tracing = "0.1.37"
rand = "0.8"
url = { version = "2.3.1", features = ["serde"] }
fedimint-server = { path = "../../fedimint-server" }
bls12_381 = { version = "0.7.1", features = [ "zeroize", "groups" ] }


[dev-dependencies]
tokio = {version = "1.26.0", features = [ "full" ] }
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
