[package]
name = "fedimint-lnv2-server"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-ln is a lightning payment service module."
license = "MIT"

[lib]
name = "fedimint_lnv2_server"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bls12_381 = { workspace = true }
erased-serde = { workspace = true }
fedimint-bitcoind = { workspace = true }
fedimint-core = { workspace = true }
fedimint-lnv2-common = { workspace = true }
fedimint-server = { workspace = true }
futures = { workspace = true }
group = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tpe = { workspace = true }
