[package]
name = "fedimint-tests"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "integrationtests contains end-to-end testing with interactions between users, lightning gateways, the blockchain, and federations, under expected, edge-case, and adversarial environments. See README for detailed instructions and examples."
license = "MIT"

[[test]]
name = "fedimint-tests"
path = "tests/tests.rs"

[dev-dependencies]
assert_matches = "1.5.0"
async-trait = "0.1.42"
bitcoin = "0.28.1"
bitcoincore-rpc = "0.15.0"
cln-rpc = "0.1"
clightningrpc = "0.2.0"
futures = "0.3.9"
itertools = "0.10.5"
lightning-invoice = "0.18.0"
ln-gateway = { path = "../ln-gateway" }
lightning = "0.0.110"
fedimint = { path = "../fedimint/" }
fedimint-api = { path = "../fedimint-api" }
fedimint-ln = { path = "../modules/fedimint-ln" }
fedimint-mint = { path = "../modules/fedimint-mint" }
fedimint-wallet = { path = "../modules/fedimint-wallet" }
mint-client = { path = "../client/client-lib" }
rand = "0.6.5"
rocksdb = "0.19.0"
serde = { version = "1.0.118", features = [ "derive" ] }
tokio = { version = "1.21.0", features = ["full"] }
tracing ="0.1.22"
tracing-subscriber = { version = "0.3.1", features = [ "env-filter" ] }
hbbft = { git = "https://github.com/fedimint/hbbft" }
threshold_crypto = { git = "https://github.com/fedimint/threshold_crypto" }
url = "2.2.2"
