[package]
name = "fedimint-tests"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "integrationtests contains end-to-end testing with interactions between users, lightning gateways, the blockchain, and federations, under expected, edge-case, and adversarial environments. See README for detailed instructions and examples."
license = "MIT"

[[test]]
name = "fedimint-tests"
path = "tests/tests.rs"

[dev-dependencies]
anyhow = "1.0.66"
assert_matches = "1.5.0"
async-trait = "0.1.64"
bitcoin = "0.29.2"
bitcoincore-rpc = "0.16.0"
cln-rpc = "0.1.1"
futures = "0.3.24"
itertools = "0.10.5"
lazy_static = "1.4.0"
lightning-invoice = "0.21.0"
ln-gateway = { path = "../gateway/ln-gateway" }
lightning = "0.0.113"
fedimint-server = { path = "../fedimint-server" }
fedimint-bitcoind = { path = "../fedimint-bitcoind" }
fedimint-core ={ path = "../fedimint-core" }
fedimint-ln-client = { path = "../modules/fedimint-ln-client" }
fedimint-ln-server = { path = "../modules/fedimint-ln-server" }
fedimint-logging = { path = "../fedimint-logging", features = ["telemetry"] }
fedimint-mint-client = { path = "../modules/fedimint-mint-client" }
fedimint-mint-server = { path = "../modules/fedimint-mint-server" }
fedimint-rocksdb = { path = "../fedimint-rocksdb" }
fedimint-sqlite = { path = "../fedimint-sqlite" }
fedimint-testing = { path = "../fedimint-testing" }
fedimint-wallet-client = { path = "../modules/fedimint-wallet-client" }
fedimint-wallet-server = { path = "../modules/fedimint-wallet-server" }
fedimintd = { path = "../fedimintd" }
mint-client = { path = "../client/client-lib" }
rand = "0.8"
serde = { version = "1.0.149", features = [ "derive" ] }
tokio = { version = "1.26.0", features = ["full"] }
tracing ="0.1.37"
url = "2.3.1"
hbbft = { git = "https://github.com/fedimint/hbbft" }
threshold_crypto = { git = "https://github.com/fedimint/threshold_crypto" }
tonic_lnd = { git = "https://github.com/fedimint/tonic_lnd", branch="lnd-client-features", features = ["lightningrpc", "routerrpc"] }
