[package]
name = "fedimint-tests"
version = "0.1.0"
edition = "2018"

[[test]]
name = "fedimint-tests"
path = "tests/tests.rs"

[dev-dependencies]
assert_matches = "1.5.0"
async-trait = "0.1.42"
bitcoin = "0.28.1"
bitcoincore-rpc = "0.15.0"
cln-rpc = "0.1"
clightningrpc = "0.2.0"
futures = "0.3.9"
itertools = "0.10.0"
lightning-invoice = "0.17.0"
ln-gateway = { path = "../ln-gateway" }
lightning = "0.0.109"
fedimint = { path = "../fedimint/" }
fedimint-api = { path = "../fedimint-api" }
fedimint-ln = { path = "../modules/fedimint-ln" }
fedimint-mint = { path = "../modules/fedimint-mint" }
fedimint-wallet = { path = "../modules/fedimint-wallet" }
mint-client = { path = "../client/client-lib" }
rand = "0.6.5"
serde = { version = "1.0.118", features = [ "derive" ] }
tokio = { version = "1.0.1", features = ["full"] }
tracing ="0.1.22"
tracing-subscriber = { version = "0.3.1", features = [ "env-filter" ] }
hbbft = { git = "https://github.com/fedimint/hbbft" }
threshold_crypto = { git = "https://github.com/fedimint/threshold_crypto" }
