[package]
name = "fedimint-empty-common"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "fedimint-empty-common is a empty fedimint module (common types)"
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_empty_common"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
fedimint-core = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
