[package]
name = "fedimint-meta-common"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "fedimint-meta-common is a meta-consensus fedimint module. (common types)"
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_meta_common"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
