[package]
name = "fedimint-cli"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-cli is a command line interface wrapper for the client library."
license = "MIT"
readme = "../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[features]
default = ["tor"]
tor = ["fedimint-client/tor", "fedimint-api-client/tor"]

[[bin]]
name = "fedimint-cli"
path = "src/main.rs"

[lib]
name = "fedimint_cli"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bip39 = { version = "2.0.0", features = ["rand"] }
bitcoin = { workspace = true }
clap = { workspace = true }
clap_complete = "4.5.18"
fedimint-aead = { version = "=0.5.0-alpha", path = "../crypto/aead" }
fedimint-api-client = { workspace = true, default-features = false }
fedimint-bip39 = { version = "=0.5.0-alpha", path = "../fedimint-bip39" }
fedimint-client = { workspace = true, default-features = false }
fedimint-core = { workspace = true }
fedimint-ln-client = { workspace = true, features = ["cli"] }
fedimint-ln-common = { version = "=0.5.0-alpha", path = "../modules/fedimint-ln-common" }
fedimint-lnv2-client = { workspace = true, features = ["cli"] }
fedimint-logging = { workspace = true }
fedimint-meta-client = { workspace = true, features = ["cli"] }
fedimint-meta-common = { workspace = true }
fedimint-mint-client = { workspace = true }
fedimint-mint-common = { workspace = true }
fedimint-rocksdb = { workspace = true }
fedimint-wallet-client = { version = "=0.5.0-alpha", path = "../modules/fedimint-wallet-client", features = [ "cli" ] }
fs-lock = "0.1.4"
futures = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
lightning-invoice = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { version = "0.3.36", features = ["formatting"] }
tokio = { workspace = true, features = ["full", "tracing"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { version = "2.5.2", features = ["serde"] }

[build-dependencies]
fedimint-build = { workspace = true }
