[package]
name = "fedimint-cli"
version = "0.3.4-rc.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-cli is a command line interface wrapper for the client library."
license = "MIT"
readme = "../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "fedimint-cli"
path = "src/main.rs"

[lib]
name = "fedimint_cli"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.81"
async-trait = "0.1.77"
base64 = "0.22.0"
bip39 = { version = "2.0.0", features = ["rand"] }
bitcoin = "0.29.2"
bitcoin_hashes = "0.11.0"
time = { version = "0.3.34", features = [ "formatting" ] }
clap = { version = "4.5.2", features = ["derive", "std", "help", "usage", "error-context", "suggestions", "env" ], default-features = false }
futures = "0.3.30"
itertools = "0.12.1"
lightning-invoice = { version = "0.26.0", features = [ "serde" ] }
fedimint-aead = { version = "=0.3.4-rc.0", path = "../crypto/aead" }
fedimint-bip39 = { version = "=0.3.4-rc.0", path = "../fedimint-bip39" }
fedimint-client = { version = "=0.3.4-rc.0", path = "../fedimint-client" }
fedimint-core = { version = "=0.3.4-rc.0", path = "../fedimint-core" }
fedimint-rocksdb = { version = "=0.3.4-rc.0", path = "../fedimint-rocksdb" }
fedimint-mint-client = { version = "=0.3.4-rc.0", path = "../modules/fedimint-mint-client" }
fedimint-mint-common = { version = "=0.3.4-rc.0", path = "../modules/fedimint-mint-common" }
fedimint-ln-client = { version = "=0.3.4-rc.0", path = "../modules/fedimint-ln-client" }
fedimint-ln-common = { version = "=0.3.4-rc.0", path = "../modules/fedimint-ln-common" }
fedimint-wallet-client = { version = "=0.3.4-rc.0", path = "../modules/fedimint-wallet-client" }
fedimint-logging = { version = "=0.3.4-rc.0", path = "../fedimint-logging" }
fedimint-server = { version = "=0.3.4-rc.0", path = "../fedimint-server" }
fedimint-meta-client = { version = "=0.3.4-rc.0", path = "../modules/fedimint-meta-client", features = [ "cli" ] }
fedimint-meta-common = { version = "=0.3.4-rc.0", path = "../modules/fedimint-meta-common" }
fs-lock = "0.1.3"
rand = "0.8"
serde = { version = "1.0.197", features = [ "derive" ] }
thiserror = "1.0.58"
tokio = { version = "1.36.0", features = ["full", "tracing"] }
tracing ="0.1.40"
tracing-subscriber = { version = "0.3.18", features = [ "env-filter" ] }
serde_json = { version = "1.0.114", features = ["preserve_order"] }
url = { version = "2.5.0", features = ["serde"] }
clap_complete = "4.5.1"
lnurl-rs = { version = "0.4.1", features = ["async"], default-features = false }
reqwest = { version = "0.11.26", features = [ "json", "rustls-tls" ], default-features = false }

[build-dependencies]
fedimint-build = { version = "=0.3.4-rc.0", path = "../fedimint-build" }
