[package]
name = "fedimint-cli"
version = "0.3.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-cli is a command line interface wrapper for the client library."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "fedimint-cli"
path = "src/main.rs"

[lib]
name = "fedimint_cli"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.73"
base64 = "0.20.0"
bitcoin = "0.29.2"
bitcoin_hashes = "0.11.0"
time = { version = "0.3.25", features = [ "formatting" ] }
clap = { version = "4.1.6", features = ["derive", "std", "help", "usage", "error-context", "suggestions", "env" ], default-features = false }
futures = "0.3.28"
lightning-invoice = { version = "0.26.0", features = [ "serde" ] }
fedimint-aead = { path = "../crypto/aead" }
fedimint-client = { path = "../fedimint-client" }
fedimint-core ={ path = "../fedimint-core" }
fedimint-rocksdb = { path = "../fedimint-rocksdb" }
fedimint-mint-client = { path = "../modules/fedimint-mint-client" }
fedimint-mint-common = { path = "../modules/fedimint-mint-common" }
fedimint-ln-client = { path = "../modules/fedimint-ln-client" }
fedimint-ln-common = { path = "../modules/fedimint-ln-common" }
fedimint-wallet-client = { path = "../modules/fedimint-wallet-client" }
fedimint-logging = { path = "../fedimint-logging" }
fedimint-server = { path = "../fedimint-server" }
fs-lock = "0.1.0"
rand = "0.8"
serde = { version = "1.0.149", features = [ "derive" ] }
thiserror = "1.0.39"
tokio = { version = "1.26.0", features = ["full", "tracing"] }
tracing ="0.1.37"
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
serde_json = { version = "1.0.91", features = ["preserve_order"] }
url = { version = "2.3.1", features = ["serde"] }
clap_complete = "4.3.1"

[build-dependencies]
fedimint-build = { path = "../fedimint-build" }
