[package]
name = "fedimint-cli"
version = "0.2.0-rc5"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-cli is a command line interface wrapper for the client library."
license = "MIT"
repository = "https://github.com/fedimint/fedimint"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "fedimint-cli"
path = "src/main.rs"

[lib]
name = "fedimint_cli"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.73"
base64 = "0.20.0"
bip39 = { version = "2.0.0", features = ["rand"] }
bitcoin = "0.29.2"
bitcoin_hashes = "0.11.0"
time = { version = "0.3.25", features = [ "formatting" ] }
clap = { version = "4.1.6", features = ["derive", "std", "help", "usage", "error-context", "suggestions", "env" ], default-features = false }
futures = "0.3.28"
lightning-invoice = { version = "0.26.0", features = [ "serde" ] }
fedimint-aead = { version = "0.2.0-rc5", path = "../crypto/aead" }
fedimint-bip39 = { version = "0.2.0-rc5", path = "../fedimint-bip39" }
fedimint-client = { version = "0.2.0-rc5", path = "../fedimint-client" }
fedimint-core = { version = "0.2.0-rc5", path = "../fedimint-core" }
fedimint-rocksdb = { version = "0.2.0-rc5", path = "../fedimint-rocksdb" }
fedimint-mint-client = { version = "0.2.0-rc5", path = "../modules/fedimint-mint-client" }
fedimint-mint-common = { version = "0.2.0-rc5", path = "../modules/fedimint-mint-common" }
fedimint-ln-client = { version = "0.2.0-rc5", path = "../modules/fedimint-ln-client" }
fedimint-ln-common = { version = "0.2.0-rc5", path = "../modules/fedimint-ln-common" }
fedimint-wallet-client = { version = "0.2.0-rc5", path = "../modules/fedimint-wallet-client" }
fedimint-logging = { version = "0.2.0-rc5", path = "../fedimint-logging" }
fedimint-server = { version = "0.2.0-rc5", path = "../fedimint-server" }
fs-lock = "0.1.0"
rand = "0.8"
serde = { version = "1.0.149", features = [ "derive" ] }
thiserror = "1.0.39"
tokio = { version = "1.26.0", features = ["full", "tracing"] }
tracing ="0.1.37"
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
serde_json = { version = "1.0.91", features = ["preserve_order"] }
url = { version = "2.3.1", features = ["serde"] }
clap_complete = "4.3.1"
lnurl-rs = { version = "0.3.1", features = ["async"], default-features = false }
reqwest = { version = "0.11.14", features = [ "json", "rustls-tls" ], default-features = false }

[build-dependencies]
fedimint-build = { version = "0.2.0-rc5", path = "../fedimint-build" }
