[package]
name = "fedimint-derive-secret"
version = "0.4.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "Fedimint derivable secret implementation"
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fedimint_derive_secret"
path = "src/lib.rs"


[dependencies]
anyhow = { workspace = true }
fedimint-core = { version = "=0.4.0-alpha", path = "../../fedimint-core" }
hkdf = { package = "fedimint-hkdf", version = "=0.4.0-alpha", path = "../../crypto/hkdf" }
ring = "0.17.8"
secp256k1-zkp = { version = "0.7.0", features = [ "serde" ] }
bls12_381 = "0.7.1"
