[package]
name = "fedimint-derive-secret"
version = "0.2.1-rc2"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "Fedimint derivable secret implementation"
license = "MIT"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fedimint_derive_secret"
path = "src/lib.rs"


[dependencies]
anyhow = "1.0.66"
fedimint-core = { version = "0.2.1-rc2", path = "../../fedimint-core" }
hkdf = { package = "fedimint-hkdf", version = "0.2.1-rc2", path = "../../crypto/hkdf" }
ring = "0.17.5"
secp256k1-zkp = { version = "0.7.0", features = [ "serde", "bitcoin_hashes" ] }
tbs = { package = "fedimint-tbs", version = "0.2.1-rc2", path = "../../crypto/tbs" }
