[package]
name = "fedimint-server"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-server' facilitates federated consensus with atomic broadcast and distributed configuration."
license = "MIT"
readme = "../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_server"
path = "src/lib.rs"

[dependencies]
aleph-bft = { package = "fedimint-aleph-bft", version = "0.36.0", default-features = false }
# aleph-bft-types = "0.13.0"
anyhow = { workspace = true }
async-channel = "2.3.1"
async-trait = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
bitcoin = { workspace = true }
bitcoincore-rpc = { workspace = true }
bls12_381 = { workspace = true }
bytes = { workspace = true }
fedimint-aead = { workspace = true }
fedimint-api-client = { workspace = true }
fedimint-bitcoind = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-metrics = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hyper = { workspace = true }
itertools = { workspace = true }
jsonrpsee = { version = "0.24.7", features = ["server"] }
parity-scale-codec = "3.6.12"
pin-project = "1.1.7"
rand = { workspace = true }
rand_chacha = { workspace = true }
rayon = { workspace = true }
rcgen = "=0.13.1"
serde = { workspace = true }
serde_json = { workspace = true }
sha3 = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
subtle = { workspace = true }
tar = "0.4.43"
tbs = { workspace = true }
threshold_crypto = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tokio-util = { version = "0.7.12", features = ["codec"] }
tower = { version = "0.4.13", default-features = false }
tracing = { workspace = true }

[dev-dependencies]
fedimint-dummy-common = { workspace = true }
fedimint-dummy-server = { workspace = true }
fedimint-portalloc = { workspace = true }
fedimint-testing-core = { workspace = true }
test-log = { workspace = true }

[build-dependencies]
fedimint-build = { workspace = true }
