[package]
name = "fedimint-server"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-server' facilitates federated consensus with atomic broadcast and distributed configuration."
license = "MIT"
readme = "../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fedimint_server"
path = "src/lib.rs"

[dependencies]
aleph-bft = { package = "fedimint-aleph-bft", version = "0.36.0", default-features = false }
aleph-bft-types = "0.13.0"
anyhow = { workspace = true }
async-channel = "2.3.1"
async-trait = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
bitcoin = { workspace = true }
bitcoin_hashes = { workspace = true }
bls12_381 = { workspace = true }
bytes = "1.6.0"
fedimint-aead = { version = "=0.4.0-alpha", path = "../crypto/aead" }
fedimint-api-client = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-metrics = { version = "=0.4.0-alpha", path = "../fedimint-metrics" }
futures = { workspace = true }
hex = { workspace = true }
hyper = "1"
itertools = { workspace = true }
jsonrpsee = { version = "0.23.1", features = ["server"] }
lazy_static = "1.4.0"
parity-scale-codec = "3.6.12"
pin-project = "1.1.5"
rand = { workspace = true }
rand_chacha = { workspace = true }
rcgen = "=0.13.1"
serde = { workspace = true }
serde_json = { workspace = true }
sha3 = "0.10.8"
strum = { workspace = true }
strum_macros = { workspace = true }
subtle = { workspace = true }
tar = "0.4.41"
tbs = { package = "fedimint-tbs", version = "=0.4.0-alpha", path = "../crypto/tbs" }
thiserror = { workspace = true }
threshold_crypto = { workspace = true }
tokio = { version = "1.38.0", features = ["full", "tracing"] }
tokio-rustls = { workspace = true }
tokio-stream = "0.1.15"
tokio-util = { version = "0.7.11", features = ["codec"] }
tower = { version = "0.4.13", default-features = false }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = { version = "2.5.2", features = ["serde"] }

[dev-dependencies]
fedimint-dummy-common = { path = "../modules/fedimint-dummy-common" }
fedimint-dummy-server = { path = "../modules/fedimint-dummy-server" }
fedimint-portalloc = { path = "../utils/portalloc" }
fedimint-testing = { workspace = true }
tempfile = "3.10.1"
test-log = { version = "0.2", features = ["trace"], default-features = false }

[build-dependencies]
fedimint-build = { version = "=0.4.0-alpha", path = "../fedimint-build" }
