[package]
name = "fedimint-server"
version = "0.2.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint is the main consensus code for processing transactions and REST API"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fedimint_server"
path = "src/lib.rs"

[dependencies]
fedimint-aead = { path = "../crypto/aead" }
anyhow = "1.0.66"
async-channel = "1.8.0"
async-trait = "0.1.73"
bincode = "1.3.1"
bitcoin = "0.29.2"
bitcoin_hashes = "0.11.0"
bytes = "1.4.0"
hbbft = { workspace = true }
futures = "0.3.24"
itertools = "0.10.5"
fedimint-core = { path = "../fedimint-core" }
fedimint-logging = { path = "../fedimint-logging" }
rand = "0.8"
rcgen = "=0.10.0"
secp256k1-zkp = { version = "0.7.0", features = [ "global-context", "bitcoin_hashes" ] }
serde = { version = "1.0.149", features = [ "derive" ] }
serde_json = "1.0.91"
sha3 = "0.10.5"
strum = "0.24"
strum_macros = "0.24"
tbs = { path = "../crypto/tbs" }
thiserror = "1.0.39"
tracing ="0.1.37"
url = { version = "2.3.1", features = ["serde"] }
threshold_crypto = { workspace = true }
jsonrpsee = { version = "0.16.2", features = ["server"] }
tokio = { version = "1.26.0", features = ["full", "tracing"] }
tokio-stream = "0.1.11"
tokio-rustls = "0.23.4"
tokio-util = { version = "0.7.4", features = [ "codec" ] }
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
aleph-bft = { version = "0.30.0", default-features = false }
aleph-bft-types = "0.10.0"
bitcoin_30 = { package = "bitcoin", version = "0.30.0" }
bitcoin_hashes_12 = { package = "bitcoin_hashes", version = "0.12.0" }
parity-scale-codec = "3.5.0"


[dev-dependencies]
tempfile = "3.4.0"
fedimint-dummy-common = { path = "../modules/fedimint-dummy-common" }
fedimint-dummy-server = { path = "../modules/fedimint-dummy-server" }
fedimint-testing = { path = "../fedimint-testing" }
test-log = { version = "0.2", features = [ "trace" ], default-features = false }

[build-dependencies]
fedimint-build = { path = "../fedimint-build" }
