[package]
name = "fedimint-server"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint is the main consensus code for processing transactions and REST API"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fedimint_server"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.64"
bincode = "1.3.1"
bitcoin = "0.29.2"
bitcoin_hashes = "0.11.0"
bytes = "1.4.0"
hbbft = { git = "https://github.com/jkitman/hbbft", branch = "upgrade-threshold-crypto-libs" }
futures = "0.3.24"
impl-tools = "0.6.1"
itertools = "0.10.5"
jsonrpsee = { version = "0.16.2", features = ["server"] }
fedimint-api = { path = "../fedimint-api" }
fedimint-core = { path = "../fedimint-core" }
rand = "0.8"
rayon = "1.6.1"
rcgen = "=0.10.0"
secp256k1-zkp = { version = "0.7.0", features = [ "global-context", "bitcoin_hashes" ] }
serde = { version = "1.0.149", features = [ "derive" ] }
serde_json = "1.0.91"
sha3 = "0.10.5"
strum = "0.24"
strum_macros = "0.24"
tbs = { path = "../crypto/tbs" }
thiserror = "1.0.37"
tokio = { version = "1.25.0", features = ["full"] }
tokio-stream = "0.1.11"
tokio-rustls = "0.23.4"
tokio-util = { version = "0.7.4", features = [ "codec" ] }
tracing ="0.1.37"
url = { version = "2.3.1", features = ["serde"] }
threshold_crypto = { git = "https://github.com/jkitman/threshold_crypto", branch = "upgrade-threshold-crypto-libs" }

[dev-dependencies]
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
test-log = { version = "0.2", features = [ "trace" ], default-features = false }

[build-dependencies]
fedimint-build = { path = "../fedimint-build" }
