[package]
name = "fedimint-dbtool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
path = "src/main.rs"
name = "dbtool"

[dependencies]
anyhow = "1.0.68"
bitcoin_hashes = "0.11.0"
bytes = "1.3.0"
clap = { version = "4.1.0", features  = [ "derive" ] }
fedimint-api = { path = "../fedimint-api" }
fedimint-rocksdb = { path = "../fedimint-rocksdb" }
tokio = "1.24.1"
