[package]
name = "fedimint-dbtool"
version = "0.2.0-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
path = "src/main.rs"
name = "fedimint-dbtool"

[dependencies]
anyhow = "1.0.68"
fedimint-aead = { path = "../crypto/aead" }
bitcoin_hashes = "0.11.0"
bytes = "1.4.0"
clap = { version = "4.1.6", features = ["derive", "env"] }
fedimint-core = { path = "../fedimint-core" }
fedimint-client = { path = "../fedimint-client" }
fedimint-server = { path = "../fedimint-server" }
fedimint-rocksdb = { path = "../fedimint-rocksdb" }
fedimint-mint-server = { path = "../modules/fedimint-mint-server" }
fedimint-mint-client = { path = "../modules/fedimint-mint-client" }
fedimint-ln-server = { path = "../modules/fedimint-ln-server" }
fedimint-ln-client = { path = "../modules/fedimint-ln-client" }
fedimint-logging = { path = "../fedimint-logging" }
fedimint-wallet-server = { path = "../modules/fedimint-wallet-server" }
fedimint-wallet-client = { path = "../modules/fedimint-wallet-client" }
futures = "0.3.24"
erased-serde = "0.3"
hex = { version = "0.4.3", features = ["serde"] }
ln-gateway = { path = "../gateway/ln-gateway" }
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.91"
strum = "0.24"
strum_macros = "0.24"
tokio = "1.26.0"
tracing = "0.1.37"
