[package]
name = "fedimint-dbtool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
path = "src/main.rs"
name = "dbtool"

[dependencies]
anyhow = "1.0.68"
bitcoin_hashes = "0.11.0"
bytes = "1.4.0"
clap = { version = "4.1.4", features  = [ "derive" ] }
fedimint-api = { path = "../fedimint-api" }
fedimint-core = { path = "../fedimint-core" }
fedimint-server = { path = "../fedimint-server" }
fedimint-rocksdb = { path = "../fedimint-rocksdb" }
fedimint-mint = { path = "../modules/fedimint-mint" }
fedimint-ln = { path = "../modules/fedimint-ln" }
fedimint-wallet = { path = "../modules/fedimint-wallet" }
fedimintd = { path = "../fedimintd" }
futures = "0.3.24"
erased-serde = "0.3"
hex = { version = "0.4.3", features = [ "serde"] }
mint-client = { path = "../client/client-lib" }
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.91"
strum = "0.24"
strum_macros = "0.24"
tokio = "1.25.0"
