[package]
name = "fedimint-dbtool"
version = { workspace = true }
edition = "2021"
license = "MIT"
readme = "README.md"
description = "Tool to inspect Fedimint client and server databases"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[[bin]]
path = "src/main.rs"
name = "fedimint-dbtool"

[lib]
name = "fedimint_dbtool"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
bytes = "1.6.1"
clap = { version = "4.5.11", features = ["derive", "env"] }
erased-serde = { workspace = true }
fedimint-aead = { version = "=0.5.0-alpha", path = "../crypto/aead" }
fedimint-client = { workspace = true }
fedimint-core = { workspace = true }
fedimint-ln-client = { workspace = true }
fedimint-ln-server = { version = "=0.5.0-alpha", path = "../modules/fedimint-ln-server" }
fedimint-lnv2-client = { workspace = true }
fedimint-lnv2-server = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-meta-client = { workspace = true }
fedimint-meta-server = { workspace = true }
fedimint-mint-client = { workspace = true }
fedimint-mint-server = { workspace = true }
fedimint-rocksdb = { workspace = true }
fedimint-server = { version = "=0.5.0-alpha", path = "../fedimint-server" }
fedimint-wallet-client = { version = "=0.5.0-alpha", path = "../modules/fedimint-wallet-client" }
fedimint-wallet-server = { version = "=0.5.0-alpha", path = "../modules/fedimint-wallet-server" }
futures = { workspace = true }
hex = { version = "0.4.3", features = ["serde"] }
ln-gateway = { package = "fedimint-ln-gateway", version = "=0.5.0-alpha", path = "../gateway/ln-gateway" }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tokio = "1.39.2"
tracing = { workspace = true }

[build-dependencies]
fedimint-build = { workspace = true }
