[package]
name = "minimint-wallet"
version = "0.1.0"
authors = ["elsirion <elsirion@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
native = ["bitcoin/bitcoinconsensus", "bitcoincore-rpc"]
default = []

[dependencies]
async-trait = "0.1"
bitcoin = { version = "0.27.0", features = [ "rand", "serde"] }
bitcoincore-rpc = {version = "0.14.0", optional = true}
hex = "0.4.3"
itertools = "0.10.0"
minimint-api = { path = "../../minimint-api" }
minimint-derive = { path = "../../minimint-derive" }
miniscript = { version = "6.0.0", features = [ "compiler", "use-serde" ] }
rand = "0.6.0"
secp256k1 = { version = "0.20", features = [ "serde" ] }
serde = { version = "1.0.118", features = [ "derive" ] }
thiserror = "1.0.23"
tokio = { version = "1.0.1", features = ["rt", "sync"] }
tracing ="0.1.22"
validator = { version = "0.13", features = ["derive"] }

[dev-dependencies]
test-log = { version = "0.2", features = [ "trace" ], default-features = false }
tracing-subscriber = { version = "0.3.1", features = [ "env-filter" ] }
