[package]
name = "fedimint-core-server"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-module provides common code used by both client and server. Can't be in fedimint-api because it depends on modules."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fedimint_core_server"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1.57"
bitcoin = "*"
impl-tools = "0.4.0"
fedimint-api = { path = "../../fedimint-api" }
fedimint-derive = { path = "../../fedimint-derive" }
fedimint-core-api = { path = "../api" }
rand = "0.6.5"
thiserror = "1.0.23"
