[package]
authors = { workspace = true }
description = "fedimint-ln-common is a lightning payment service module (common types)."
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-ln-common"
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[package.metadata.cargo-udeps.ignore]
# cargo udeps can't detect that one
normal = ["aquamarine"]

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_ln_common"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bitcoin = { workspace = true }
fedimint-connectors = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
iroh = { workspace = true }
lightning = { workspace = true }
lightning-invoice = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde-big-array = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
threshold_crypto = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
