[package]
name = "fedimint-ln-common"
version = "0.2.1-rc1"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-ln is a lightning payment service module."
license = "MIT"
repository = "https://github.com/fedimint/fedimint"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.cargo-udeps.ignore]
# cargo udeps can't detect that one
normal = ["aquamarine"]

[lib]
name = "fedimint_ln_common"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.73"
aquamarine = "0.3.0"
bitcoin_hashes = "0.11.0"
bitcoin = { version = "0.29.2", features = [ "rand", "serde"] }
erased-serde = "0.3"
futures = "0.3.24"
itertools = "0.10.5"
lightning = { version = "0.0.118", default-features = false, features = ["no-std"] }
lightning-invoice = { version = "0.26.0", features = [ "serde" ] }
fedimint-client = { version = "0.2.1-rc1", path = "../../fedimint-client" }
fedimint-core = { version = "0.2.1-rc1", path = "../../fedimint-core" }
secp256k1 = { version="0.24.2", default-features=false }
serde = {version = "1.0.149", features = [ "derive" ] }
serde_json = "1.0.91"
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0.39"
threshold_crypto = { workspace = true }
tracing = "0.1.37"
rand = "0.8"
url = { version = "2.3.1", features = ["serde"] }
serde-big-array = "0.5.1"

[dev-dependencies]
tokio = {version = "1.26.0", features = [ "full" ] }
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
