[package]
name = "fedimint-recoverytool"
version = "0.3.0-alpha"
edition = "2021"
authors = ["The Fedimint Developers"]
description = "recoverytool allows retrieving on-chain funds from a offline federation"
license = "MIT"

[[bin]]
name = "recoverytool"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.69"
bitcoin = "0.29.2"
clap = { version = "4.4.7", features = [ "derive", "env" ] }
fedimint-aead = { version = "0.3.0-alpha", path = "../crypto/aead" }
fedimint-core = { version = "0.3.0-alpha", path = "../fedimint-core" }
fedimint-rocksdb = { version = "0.3.0-alpha", path = "../fedimint-rocksdb" }
fedimint-server = { version = "0.3.0-alpha", path = "../fedimint-server" }
fedimint-wallet-server = { version = "0.3.0-alpha", path = "../modules/fedimint-wallet-server" }
fedimint-logging = { version = "0.3.0-alpha", path = "../fedimint-logging" }
fedimint-ln-common = { version = "0.3.0-alpha", path = "../modules/fedimint-ln-common" }
fedimint-ln-server = { version = "0.3.0-alpha", path = "../modules/fedimint-ln-server" }
fedimint-mint-server = { version = "0.3.0-alpha", path = "../modules/fedimint-mint-server" }
futures = "0.3.26"
miniscript = { version = "9.0.2" }
secp256k1 = { version = "0.24.3", features = [ "serde", "global-context" ] }
serde = { version = "1.0.152", features = [ "derive" ] }
serde_json = "1.0.93"
tokio = { version = "1.26.0", features = [ "rt-multi-thread", "macros" ] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[dev-dependencies]
rand = "0.8.5"
