[package]
name = "fedimint-fuzz"
edition = "2021"
authors = ["The Fedimint Developers"]
version = "0.3.0-alpha"
publish = false
license = "MIT"
readme = "../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata]
cargo-fuzz = true

[dependencies]
honggfuzz = { version = "0.5.55", default-features = false }
fedimint-core = { version = "0.3.0-alpha", path = "../fedimint-core" }

# cargo-deny just needs at least one `bin` defined
[lib]
name = "fedimint_fuzz"
path = "src/lib.rs"

[[bin]]
name = "vec"
path = "src/bin/vec.rs"
