[package]
name = "fedimint-dummy-server"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-dummy is a dummy example fedimint module."
license = "MIT"

[lib]
name = "fedimint_dummy_server"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1"
bitcoin_hashes = "0.11.0"
erased-serde = "0.3"
futures = "0.3"
fedimint-core = { path = "../../fedimint-core" }
fedimint-dummy-common = { path = "../fedimint-dummy-common" }
rand = "0.8"
serde = { version = "1.0.149", features = [ "derive" ] }
secp256k1 = "0.27.0"
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0.39"
fedimint-server = { path = "../../fedimint-server" }
tracing = "0.1.37"
threshold_crypto = { git = "https://github.com/fedimint/threshold_crypto" }
tokio = { version = "1.26.0", features = ["sync"] }
