[package]
name = "fedimint-dummy-common"
version = "0.2.0-rc4"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-dummy is a dummy example fedimint module."
license = "MIT"
repository = "https://github.com/fedimint/fedimint"

[lib]
name = "fedimint_dummy_common"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.73"
bitcoin_hashes = "0.11.0"
erased-serde = "0.3"
futures = "0.3"
fedimint-core = { version = "0.2.0-rc4", path = "../../fedimint-core" }
rand = "0.8"
serde = { version = "1.0.149", features = [ "derive" ] }
secp256k1 = "0.24.2"
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0.39"
tracing = "0.1.37"
threshold_crypto = { workspace = true }
