[package]
name = "fedimint-dummy-common"
version = "0.3.4-rc.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-dummy is a dummy example fedimint module."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_dummy_common"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.81"
async-trait = "0.1.77"
bitcoin_hashes = "0.11.0"
erased-serde = "0.4"
futures = "0.3"
fedimint-core = { version = "=0.3.4-rc.0", path = "../../fedimint-core" }
rand = "0.8"
serde = { version = "1.0.197", features = [ "derive" ] }
secp256k1 = "0.24.3"
strum = "0.26"
strum_macros = "0.26"
thiserror = "1.0.58"
tracing = "0.1.40"
threshold_crypto = { workspace = true }
