[package]
name = "fedimint-mint-tests"
version = "0.3.4-rc.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-mint-tests contains integration tests for the mint module"
license = "MIT"
publish = false

[[test]]
name = "fedimint_mint_tests"
path = "tests/tests.rs"

[dependencies]
anyhow = "1.0.81"
bitcoin_hashes = "0.11.0"
fedimint-dummy-common = { path = "../fedimint-dummy-common" }
fedimint-dummy-client = { path = "../fedimint-dummy-client" }
fedimint-dummy-server = { path = "../fedimint-dummy-server" }
fedimint-mint-common = { path = "../fedimint-mint-common" }
fedimint-mint-client = { path = "../fedimint-mint-client" }
fedimint-mint-server = { path = "../fedimint-mint-server" }
fedimint-testing = { path = "../../fedimint-testing" }
fedimint-client = { path = "../../fedimint-client" }
fedimint-core ={ path = "../../fedimint-core" }
fedimint-server = { path = "../../fedimint-server" }
fedimint-logging = { path = "../../fedimint-logging" }
futures = "0.3"
tokio = { version = "1.36.0", features = ["sync"] }
tracing = "0.1.40"
rand = "0.8"
secp256k1 = "0.24.3"
serde = { version = "1.0.197", features = [ "derive" ] }
tbs = { package = "fedimint-tbs", version = "=0.3.4-rc.0", path = "../../crypto/tbs" }
threshold_crypto = { workspace = true }
ff = "0.12.1"
strum = "0.26"
strum_macros = "0.26"
