[package]
name = "fedimint-mint-tests"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-mint-tests contains integration tests for the mint module"
license = "MIT"
publish = false

[[test]]
name = "fedimint_mint_tests"
path = "tests/tests.rs"

[dependencies]
anyhow = { workspace = true }
bitcoin_hashes = { workspace = true }
bls12_381 = { workspace = true }
devimint = { workspace = true }
fedimint-client = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-mint-client = { path = "../fedimint-mint-client" }
fedimint-mint-common = { path = "../fedimint-mint-common" }
fedimint-mint-server = { path = "../fedimint-mint-server" }
fedimint-testing = { workspace = true }
ff = "0.13.0"
futures = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
tbs = { package = "fedimint-tbs", version = "=0.4.2-rc.2", path = "../../crypto/tbs" }
threshold_crypto = { workspace = true }
tokio = { version = "1.38.0", features = ["sync"] }
tracing = { workspace = true }

[dev-dependencies]
fedimint-dummy-client = { path = "../fedimint-dummy-client", version = "=0.4.2-rc.2" }
fedimint-dummy-common = { path = "../fedimint-dummy-common", version = "=0.4.2-rc.2" }
fedimint-dummy-server = { path = "../fedimint-dummy-server", version = "=0.4.2-rc.2" }
