[package]
name = "fedimint-api-client"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-api-client provides common code used by client."
license = "MIT"
readme = "../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.cargo-udeps.ignore]
development = ["tokio-test"]

[features]
tor = ["arti-client", "strum", "curve25519-dalek"]

[lib]
name = "fedimint_api_client"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bitcoin = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
jsonrpsee-core = { version = "0.24.2" }
lru = "0.12.4"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio-test = "0.4.4"
tracing-subscriber = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
jsonrpsee-ws-client = { version = "0.24.2", features = [
    "tls",
], default-features = false }
tokio = { workspace = true, features = ["full", "tracing"] }
tokio-rustls = { version = "0.26.0", default-features = false, features = [
    "logging",
    "tls12",
    "ring",
] }
webpki-roots = { version = "0.26.3" }
rustls-pki-types = { version = "1.8.0" }
arti-client = { version = "0.20.0", features = ["tokio", "rustls", "onion-service-client"], default-features = false, package = "fedimint-arti-client", optional = true }
strum = { version = "0.26.3", optional = true }
# We need to pin this arti's `curve25519-dalek` dependency, due to `https://rustsec.org/advisories/RUSTSEC-2024-0344` vulnerability
# It's been updated by https://gitlab.torproject.org/tpo/core/arti/-/merge_requests/2211, should be removed in next release.
curve25519-dalek = { version = ">=4.1.3", optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
jsonrpsee-wasm-client = "0.24.2"
async-lock = "3.4"
# getrandom is transitive dependency of rand
# on wasm, we need to enable the js backend
# see https://docs.rs/getrandom/latest/getrandom/#indirect-dependencies and https://docs.rs/getrandom/latest/getrandom/#webassembly-support
getrandom = { version = "0.2.15", features = ["js"] }
gloo-timers = { version = "0.3.0", features = ["futures"] }
wasm-bindgen-futures = "0.4.42"
js-sys = "0.3.69"
