[package]
name = "fedimint-ln-client"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-ln is a lightning payment service module."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.cargo-udeps.ignore]
# cargo udeps can't detect that one
normal = ["aquamarine"]

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_ln_client"
path = "src/lib.rs"

[features]
default =[]
cli = ["dep:clap" ]

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, optional = true }
async-trait = { workspace = true }
async-stream = "0.3.5"
aquamarine = "0.5.0"
bitcoin = { workspace = true }
erased-serde = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
lightning-invoice = { version = "0.31.0", features = [ "serde" ] }
lnurl-rs = { version = "0.6.0", features = ["async"], default-features = false }
fedimint-client = { workspace = true }
fedimint-core = { workspace = true }
fedimint-api-client = { workspace = true }
fedimint-ln-common = { version = "=0.4.3-rc.2", path = "../fedimint-ln-common" }
fedimint-logging = { workspace = true }
secp256k1 = { version="0.27.0", default-features=false }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1.38.0", features = ["macros"] }
tracing = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
