[package]
name = "fedimint-client"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "mint-client provides a library for sending transactions to the federation."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fedimint_client"
path = "src/lib.rs"


[dependencies]
bitcoin = "0.29.2"
fedimint-core  = { path = "../fedimint-core/" }
thiserror = "1.0.30"

[dev-dependencies]
fedimint-core ={ path = "../fedimint-core/" }
