[package]
name = "fedimint-client"
version = "0.2.1-rc3"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-client provides a library for sending transactions to the federation."
license = "MIT"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.cargo-udeps.ignore]
# cargo udeps can't detect that one
normal = ["aquamarine"]

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_client"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.69"
aquamarine = "0.3.1"
async-stream = "0.3.5"
async-trait = "0.1.73"
bitcoin = "0.29.2"
bitcoin_hashes = "0.11.0"
fedimint-core  = { version = "0.2.1-rc3", path = "../fedimint-core/" }
fedimint-derive-secret = { version = "0.2.1-rc3", path = "../crypto/derive-secret" }
fedimint-aead = { version = "0.2.1-rc3", path = "../crypto/aead" }
fedimint-logging = { version = "0.2.1-rc3", path = "../fedimint-logging" }
futures = "0.3.26"
itertools = "0.10.5"
rand = "0.8.5"
secp256k1-zkp = "0.7.0"
serde = "1.0.152"
serde_json = "1.0.91"
strum = "0.24.1"
strum_macros = "0.24.1"
thiserror = "1.0.39"
tokio = { version = "1.26.0", features = [ "time", "macros" ] }
tracing = "0.1.37"

[target.'cfg(target_family = "wasm")'.dependencies]
ring = { version = "0.17.5", features = ["wasm32_unknown_unknown_js"] }

[dev-dependencies]
tracing-test = "0.2.4"

[build-dependencies]
fedimint-build = { version = "0.2.1-rc3", path = "../fedimint-build" }
