[package]
name = "fedimint-client"
version = "0.3.4-rc.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-client provides a library for sending transactions to the federation."
license = "MIT"
readme = "../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.cargo-udeps.ignore]
# cargo udeps can't detect that one
normal = ["aquamarine"]

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_client"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.81"
aquamarine = "0.5.0"
async-stream = "0.3.5"
async-trait = "0.1.77"
bitcoin = "0.29.2"
bitcoin_hashes = "0.11.0"
fedimint-core  = { version = "=0.3.4-rc.0", path = "../fedimint-core/" }
fedimint-derive-secret = { version = "=0.3.4-rc.0", path = "../crypto/derive-secret" }
fedimint-aead = { version = "=0.3.4-rc.0", path = "../crypto/aead" }
fedimint-logging = { version = "=0.3.4-rc.0", path = "../fedimint-logging" }
futures = "0.3.30"
itertools = "0.12.1"
rand = "0.8.5"
secp256k1-zkp = "0.7.0"
serde = "1.0.197"
serde_json = "1.0.114"
strum = "0.26.2"
strum_macros = "0.26.2"
thiserror = "1.0.58"
tokio = { version = "1.36.0", features = [ "time", "macros" ] }
tokio-stream = { version = "0.1.14", features = [ "time", "sync" ] }
tracing = "0.1.40"
reqwest = { version = "0.12.2", features = ["json", "rustls-tls"], default-features = false }

[target.'cfg(target_family = "wasm")'.dependencies]
ring = { version = "0.17.8", features = ["wasm32_unknown_unknown_js"] }

[dev-dependencies]
tracing-test = "0.2.4"

[build-dependencies]
fedimint-build = { version = "=0.3.4-rc.0", path = "../fedimint-build" }
