[package]
name = "fedimint-client"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "mint-client provides a library for sending transactions to the federation."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fedimint_client"
path = "src/lib.rs"


[dependencies]
anyhow = "1.0.69"
async-trait = "0.1.66"
bitcoin_hashes = "0.11.0"
fedimint-core  = { path = "../fedimint-core/" }
fedimint-logging = { path = "../fedimint-logging" }
futures = "0.3.26"
itertools = "0.10.5"
rand = "0.8.5"
secp256k1-zkp = "0.7.0"
serde = "1.0.152"
serde_json = "1.0.91"
tokio = { version = "1.26.0", features = [ "time", "macros" ] }
tracing = "0.1.37"

[dev-dependencies]
impl-tools = "0.8.0"
tracing-test = "0.2.4"
