[package]
name = "fedimint-dummy-client"
version = "0.2.2-rc7"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-dummy is a dummy example fedimint module."
license = "MIT"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_dummy_client"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1.73"
anyhow = "1.0.66"
fedimint-dummy-common = { version = "0.2.2-rc7", path = "../fedimint-dummy-common" }
fedimint-client = { version = "0.2.2-rc7", path = "../../fedimint-client" }
fedimint-core = { version = "0.2.2-rc7", path = "../../fedimint-core" }
futures = "0.3"
erased-serde = "0.3"
rand = "0.8.5"
secp256k1 = "0.24.2"
serde = {version = "1.0.149", features = [ "derive" ] }
strum = "0.24"
strum_macros = "0.24"
tracing = "0.1.37"
thiserror = "1.0.39"
threshold_crypto = { workspace = true }
