[package]
name = "fedimint-dummy-client"
version = "0.4.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-dummy is a dummy example fedimint module."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_dummy_client"
path = "src/lib.rs"

[dependencies]
async-trait = { workspace = true }
anyhow = { workspace = true }
fedimint-dummy-common = { version = "=0.4.0-alpha", path = "../fedimint-dummy-common" }
fedimint-client = { workspace = true }
fedimint-core = { workspace = true }
fedimint-api-client = { workspace = true }
futures = { workspace = true }
erased-serde = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
