[package]
name = "fedimint-dummy-client"
version = "0.3.4-rc.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-dummy is a dummy example fedimint module."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_dummy_client"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1.77"
anyhow = "1.0.81"
fedimint-dummy-common = { version = "=0.3.4-rc.0", path = "../fedimint-dummy-common" }
fedimint-client = { version = "=0.3.4-rc.0", path = "../../fedimint-client" }
fedimint-core = { version = "=0.3.4-rc.0", path = "../../fedimint-core" }
futures = "0.3"
erased-serde = "0.4"
rand = "0.8.5"
secp256k1 = "0.24.3"
serde = {version = "1.0.197", features = [ "derive" ] }
strum = "0.26"
strum_macros = "0.26"
tracing = "0.1.40"
thiserror = "1.0.58"
threshold_crypto = { workspace = true }
