[package]
name = "fedimint-dummy-tests"
version = "0.2.1-rc2"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-dummy is a dummy example fedimint module."
license = "MIT"
publish = false

[[test]]
name = "fedimint_dummy_tests"
path = "tests/tests.rs"

[dependencies]
anyhow = "1.0.66"
fedimint-client = { path = "../../fedimint-client" }
fedimint-core ={ path = "../../fedimint-core" }
fedimint-dummy-client = { path = "../fedimint-dummy-client" }
fedimint-dummy-common = { path = "../fedimint-dummy-common" }
fedimint-dummy-server = { path = "../fedimint-dummy-server" }
fedimint-logging = { path = "../../fedimint-logging" }
fedimint-server = { path = "../../fedimint-server" }
fedimint-testing = { path = "../../fedimint-testing" }
rand = "0.8"
secp256k1 = "0.24.2"
tokio = { version = "1.26.0", features = ["sync"] }
tracing = "0.1.37"

[dev-dependencies]
threshold_crypto = { workspace = true }
