[package]
name = "fedimint-dummy-tests"
version = "0.4.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-dummy is a dummy example fedimint module."
license = "MIT"
publish = false

[[test]]
name = "fedimint_dummy_tests"
path = "tests/tests.rs"

[dependencies]
anyhow = { workspace = true }
fedimint-client = { path = "../../fedimint-client" }
fedimint-core ={ path = "../../fedimint-core" }
fedimint-dummy-client = { path = "../fedimint-dummy-client" }
fedimint-dummy-common = { path = "../fedimint-dummy-common" }
fedimint-dummy-server = { path = "../fedimint-dummy-server" }
fedimint-logging = { path = "../../fedimint-logging" }
fedimint-server = { path = "../../fedimint-server" }
fedimint-testing = { path = "../../fedimint-testing" }
futures = { workspace = true }
rand = { workspace = true }
secp256k1 = "0.24.3"
strum = { workspace = true }
strum_macros = { workspace = true }
tokio = { version = "1.36.0", features = ["sync"] }
tracing = { workspace = true }

[dev-dependencies]
threshold_crypto = { workspace = true }
