[package]
name = "fedimint-dummy-tests"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-dummy is a dummy example fedimint module."
license = "MIT"
publish = false

[[test]]
name = "fedimint_dummy_tests"
path = "tests/tests.rs"

[dependencies]
anyhow = { workspace = true }
fedimint-client = { workspace = true }
fedimint-core = { workspace = true }
fedimint-dummy-client = { workspace = true }
fedimint-dummy-common = { workspace = true }
fedimint-dummy-server = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-testing = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
