[package]
name = "fedimint-dummy-tests"
version = "0.4.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-dummy is a dummy example fedimint module."
license = "MIT"
publish = false

[[test]]
name = "fedimint_dummy_tests"
path = "tests/tests.rs"

[dependencies]
anyhow = { workspace = true }
fedimint-client = { path = "../../fedimint-client" }
fedimint-core = { workspace = true }
fedimint-dummy-client = { path = "../fedimint-dummy-client" }
fedimint-dummy-common = { path = "../fedimint-dummy-common" }
fedimint-dummy-server = { path = "../fedimint-dummy-server" }
fedimint-logging = { path = "../../fedimint-logging" }
fedimint-testing = { path = "../../fedimint-testing" }
futures = { workspace = true }
rand = { workspace = true }
strum = { workspace = true }
tokio = { version = "1.37.0", features = ["sync"] }
tracing = { workspace = true }
