[package]
authors = { workspace = true }
description = "fedimint-gw-client is a crate for servicing lightning payments on behalf of fedimint clients"
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-gw-client"
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[package.metadata.cargo-udeps.ignore]
# cargo udeps can't detect that one
normal = ["aquamarine"]

[lib]
name = "fedimint_gw_client"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
aquamarine = { workspace = true }
async-stream = { workspace = true }
async-trait = { workspace = true }
bitcoin = { workspace = true }
erased-serde = { workspace = true }
fedimint-api-client = { workspace = true }
fedimint-client = { workspace = true }
fedimint-client-module = { workspace = true }
fedimint-connectors = { workspace = true }
fedimint-core = { workspace = true }
fedimint-derive-secret = { workspace = true }
fedimint-eventlog = { workspace = true }
fedimint-gwv2-client = { workspace = true }
fedimint-lightning = { workspace = true }
fedimint-ln-client = { workspace = true }
fedimint-ln-common = { workspace = true }
fedimint-lnv2-common = { workspace = true }
futures = { workspace = true }
lightning-invoice = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true, features = ["log"] }

[lints]
workspace = true
