services:
  fedimintd:
    image: fedimint/fedimintd:da61291173e71a11358e1cd4154e649cf413d9e9
    ports:
      - 8173:8173/tcp # p2p tls
      - 8173:8173/udp # p2p iroh
      - 8174:8174/udp # api iroh
      - 127.0.0.1:8175:8175/tcp # ui
    volumes:
      - fedimintd_data:/data
    environment:
      - FM_FORCE_IROH=1
      - FM_BITCOIN_NETWORK=signet
      - FM_BITCOIN_RPC_KIND=esplora
      - FM_BITCOIN_RPC_URL=https://mutinynet.com/api
      - FM_BIND_P2P=0.0.0.0:8173
      - FM_BIND_API_IROH=0.0.0.0:8174
      - FM_BIND_API_WS=172.25.0.11:8174
      - FM_BIND_UI=172.25.0.11:8175
    networks:
      fedimint_network:
        ipv4_address: 172.25.0.11
    restart: always

networks:
  fedimint_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1

volumes:
  fedimintd_data:
