[package]
name = "fedimint-empty-server"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "fedimint-empty is a empty fedimint module, good template for a new module."
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_empty_server"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
erased-serde = { workspace = true }
fedimint-core = { workspace = true }
fedimint-empty-common = { workspace = true }
fedimint-server-core = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
