[package]
name = "ln-gateway"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "ln-gateway is a core lightning plugin which allows a Lightning node operator to receive or pay Lightning invoices on behalf of fedimint users."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ln_gateway"
path = "src/lib.rs"

[[bin]]
name = "ln_gateway"
path = "src/bin/ln_gateway.rs"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.59"
axum = "0.5.16"
axum-macros = "0.2.3"
bitcoin_hashes = "0.11.0"
bitcoin = { version = "0.29.2", features = ["serde"] }
cln-rpc = "0.1.1"
cln-plugin = "0.1.1"
futures = "0.3.24"
hex = "0.4.3"
lightning-invoice = "0.20.0"
fedimint-server = { path = "../../fedimint-server/" }
fedimint-api = { path = "../../fedimint-api" }
fedimint-rocksdb = { path = "../../fedimint-rocksdb" }
mint-client = { path = "../../client/client-lib" }
rand = "0.8"
reqwest = { version = "0.11.13", features = [ "json" ], default-features = false }
secp256k1 = "0.24.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.89"
thiserror = "1.0.37"
tracing = { version = "0.1.37", default-features = false, features= ["log", "attributes", "std"] }
tokio = {version = "1.23", features = ["full"]}
tower-http = { version = "0.3.4", features = ["cors", "auth"] }
url = { version = "2.3.1", features = ["serde"] }

[build-dependencies]
fedimint-build = { path = "../../fedimint-build" }

