[package]
name = "fedimint-ln-gateway"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-ln-gateway sends/receives Lightning Network payments on behalf of Fedimint clients"
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[features]
default = ["tor"]
tor = ["fedimint-client/tor", "fedimint-api-client/tor"]

[[bin]]
name = "gatewayd"
path = "src/bin/gatewayd.rs"

[[bin]]
name = "gateway-cln-extension"
path = "src/bin/cln_extension.rs"

[lib]
name = "ln_gateway"
path = "src/lib.rs"

[[test]]
name = "gatewayd-tests"
path = "tests/tests.rs"

[dependencies]
anyhow = { workspace = true }
aquamarine = { workspace = true }
async-stream = { workspace = true }
async-trait = { workspace = true }
axum = "0.7.5"
bitcoin = { workspace = true }
bitcoin_hashes = { workspace = true }
clap = { workspace = true }
# cln-plugin made semver incompatible change
cln-plugin = "=0.1.7"
cln-rpc = { workspace = true }
erased-serde = { workspace = true }
esplora-client = { version = "0.6.0", default-features = false, features = ["async", "async-https-rustls"] }
fedimint-api-client = { workspace = true, default-features = false }
fedimint-client = { workspace = true, default-features = false }
fedimint-core = { workspace = true }
fedimint-ln-client = { workspace = true }
fedimint-ln-common = { workspace = true }
fedimint-lnv2-client = { workspace = true }
fedimint-lnv2-common = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-mint-client = { workspace = true }
fedimint-rocksdb = { workspace = true }
fedimint-wallet-client = { version = "=0.5.0-alpha", path = "../../modules/fedimint-wallet-client" }
futures = { workspace = true }
hex = { workspace = true }
ldk-node = "0.3.0"
lightning = { workspace = true }
lightning-invoice = { workspace = true }
prost = "0.13.1"
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { version = "0.12.1", features = ["transport", "tls"] }
tonic_lnd = { workspace = true }
tower-http = { version = "0.5.2", features = ["cors", "auth"] }
tpe = { package = "fedimint-tpe", version = "=0.5.0-alpha", path = "../../crypto/tpe" }
tracing = { version = "0.1.40", default-features = false, features = ["log", "attributes", "std"] }
url = { version = "2.5.2", features = ["serde"] }

[dev-dependencies]
assert_matches = { workspace = true }
fedimint-dummy-client = { path = "../../modules/fedimint-dummy-client" }
fedimint-dummy-common = { path = "../../modules/fedimint-dummy-common" }
fedimint-dummy-server = { path = "../../modules/fedimint-dummy-server" }
fedimint-ln-client = { workspace = true }
fedimint-ln-common = { path = "../../modules/fedimint-ln-common" }
fedimint-ln-server = { path = "../../modules/fedimint-ln-server" }
fedimint-lnv2-server = { workspace = true }
fedimint-mint-client = { workspace = true }
fedimint-testing = { workspace = true }
fedimint-unknown-common = { path = "../../modules/fedimint-unknown-common" }
fedimint-unknown-server = { path = "../../modules/fedimint-unknown-server" }
fedimint-wallet-client = { path = "../../modules/fedimint-wallet-client" }
threshold_crypto = { workspace = true }

[build-dependencies]
fedimint-build = { workspace = true }
tonic-build = "0.12.1"
