[package]
name = "fedimint-ln-gateway"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-ln-gateway sends/receives Lightning Network payments on behalf of Fedimint clients"
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[features]
default = ["tor"]
tor = ["fedimint-client/tor", "fedimint-api-client/tor"]

[[bin]]
name = "gatewayd"
path = "src/bin/gatewayd.rs"

[[bin]]
name = "gateway-cln-extension"
path = "src/bin/cln_extension.rs"

[lib]
name = "ln_gateway"
path = "src/lib.rs"

[[test]]
name = "gatewayd-tests"
path = "tests/tests.rs"

[dependencies]
anyhow = { workspace = true }
aquamarine = { workspace = true }
async-stream = { workspace = true }
async-trait = { workspace = true }
axum = { version = "0.7.7", features = [ "json" ] }
axum-macros = "0.4.2"
bitcoin = { workspace = true }
clap = { workspace = true }
cln-plugin = "0.2.0"
cln-rpc = { workspace = true }
erased-serde = { workspace = true }
esplora-client = { workspace = true }
fedimint-api-client = { path = "../../fedimint-api-client", version = "=0.6.0-alpha", default-features = false }
fedimint-bip39 = { version = "=0.6.0-alpha", path = "../../fedimint-bip39" }
fedimint-client = { path = "../../fedimint-client", version = "=0.6.0-alpha", default-features = false }
fedimint-core = { workspace = true }
fedimint-ln-client = { workspace = true }
fedimint-ln-common = { workspace = true }
fedimint-lnv2-client = { workspace = true }
fedimint-lnv2-common = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-mint-client = { workspace = true }
fedimint-rocksdb = { workspace = true }
fedimint-wallet-client = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
hex = { workspace = true }
ldk-node = "0.4.2"
lightning = { workspace = true }
lightning-invoice = { workspace = true }
prost = "0.13.3"
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { version = "0.12.3", features = ["transport", "tls"] }
tonic_lnd = { workspace = true }
tower-http = { version = "0.6.1", features = ["cors", "auth"] }
tpe = { workspace = true }
tracing = { workspace = true, features = ["log"] }
url = { workspace = true, features = ["serde"] }

[dev-dependencies]
assert_matches = { workspace = true }
fedimint-dummy-client = { workspace = true }
fedimint-dummy-common = { workspace = true }
fedimint-dummy-server = { workspace = true }
fedimint-ln-server = { workspace = true }
fedimint-lnv2-server = { workspace = true }
fedimint-testing = { workspace = true }
fedimint-unknown-common = { workspace = true }
fedimint-unknown-server = { workspace = true }

[build-dependencies]
fedimint-build = { workspace = true }
