[package]
authors = ["The Fedimint Developers"]
description = "fedimint walletv2 enables the integrator to send and receive funds on-chain. (client)"
edition = "2021"
license = "MIT"
name = "fedimint-walletv2-client"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"
version = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_walletv2_client"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-stream = { workspace = true }
async-trait = { workspace = true }
bitcoin = { workspace = true }
clap = { workspace = true }
erased-serde = { workspace = true }
fedimint-api-client = { workspace = true }
fedimint-client = { workspace = true }
fedimint-client-module = { workspace = true }
fedimint-core = { workspace = true }
fedimint-derive-secret = { workspace = true }
fedimint-eventlog = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-walletv2-common = { workspace = true }
futures = { workspace = true }
secp256k1 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
