[package]
name = "fedimint-server-ui"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "fedimint-server-ui is a server-side rendered admin web UI for fedimintd."
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[lib]
name = "fedimint_server_ui"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true, features = ["macros"] }
axum-extra = { version = "0.10.1", features = ["cookie"] }
chrono = "0.4"
fedimint-core = { workspace = true }
fedimint-lnv2-server = { workspace = true }
fedimint-meta-server = { workspace = true }
fedimint-server-core = { workspace = true }
fedimint-wallet-server = { workspace = true }
maud = "0.27.0"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
