[package]
authors = { workspace = true }
description = "fedimint-server-ui is a server-side rendered admin web UI for fedimintd."
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-server-ui"
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[lib]
name = "fedimint_server_ui"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true, features = ["macros"] }
axum-extra = { workspace = true, features = ["cookie", "form"] }
chrono = { workspace = true }
fedimint-core = { workspace = true }
fedimint-lnv2-server = { workspace = true }
fedimint-meta-server = { workspace = true }
fedimint-metrics = { workspace = true }
fedimint-server-core = { workspace = true }
fedimint-ui-common = { workspace = true }
fedimint-wallet-server = { workspace = true }
maud = { workspace = true }
qrcode = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
