[package]
name = "fedimint-empty-client"
version = "0.4.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-empty is an empty fedimint module, good template for a new module."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_empty_client"
path = "src/lib.rs"

[dependencies]
async-trait = { workspace = true }
anyhow = { workspace = true }
fedimint-empty-common = { version = "=0.4.0-alpha", path = "../fedimint-empty-common" }
fedimint-client = { version = "=0.4.0-alpha", path = "../../fedimint-client" }
fedimint-core = { version = "=0.4.0-alpha", path = "../../fedimint-core" }
futures = { workspace = true }
erased-serde = { workspace = true }
serde = {version = "1.0.197", features = [ "derive" ] }
strum = { workspace = true }
strum_macros = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
