[package]
name = "fediwallet"
version = "0.1.0"
authors = ["elsirion <elsirion@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
bincode = "1"
bitcoin = { version = "0.26.0", features = [ "rand", "serde", "bitcoinconsensus" ] }
bitcoincore-rpc-async = "3.0.1"
config = { path = "../config" }
futures = "0.3"
hex = "0.4.3"
itertools = "0.10.0"
minimint-derive = { path = "../minimint-derive" }
miniscript = { version = "5.1.0", features = [ "compiler" ] }
mint-api = { path = "../mint-api" }
musig = { path = "../crypto/musig" }
rand = "0.6.0"
secp256k1 = { version = "0.20.1", features = [ "serde" ] }
serde = { version = "1.0.118", features = [ "derive" ] }
thiserror = "1.0.23"
tokio = { version = "1.0.1", features = ["full"] }
tracing ="0.1.22"