[package]
name = "fedimint-bip39"
version = "0.3.0-alpha"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fedimint_bip39"
path = "./src/lib.rs"

[dependencies]
bip39 = { version = "2.0.0", features = ["rand"] }
fedimint-client = { path = "../fedimint-client" }
fedimint-core = { path = "../fedimint-core" }
rand = "0.8.5"
