[package]
name = "fedimint-bip39"
version = "0.2.0-rc4"
edition = "2021"
license = "MIT"
description = "Allows using bip39 mnemonic phrases to generate fedimint client keys"
repository = "https://github.com/fedimint/fedimint"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fedimint_bip39"
path = "./src/lib.rs"

[dependencies]
bip39 = { version = "2.0.0", features = ["rand"] }
fedimint-client = { version = "0.2.0-rc4", path = "../fedimint-client" }
fedimint-core = { version = "0.2.0-rc4", path = "../fedimint-core" }
rand = "0.8.5"
