[package]
name = "fedimint-derive"
version = "0.4.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-derive provides helper macros for serialization."
license = "MIT"
readme = "../README.md"
repository = "https://github.com/fedimint/fedimint"

[lib]
proc-macro = true
name = "fedimint_derive"
path = "src/lib.rs"

[features]
diagnostics = []

[dependencies]
itertools = { workspace = true }
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
