[package]
authors = { workspace = true }
description = "Tool for retrieving on-chain funds from a decommissioned Fedimint federation"
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-recoverytool"
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[[bin]]
name = "fedimint-recoverytool"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
bitcoin = { workspace = true }
clap = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-redb = { workspace = true }
fedimint-rocksdb = { workspace = true }
fedimint-server = { workspace = true }
fedimint-wallet-server = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
miniscript = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing = { workspace = true }

[dev-dependencies]
rand = { workspace = true }

[build-dependencies]
fedimint-build = { workspace = true }

[lints]
workspace = true
