[package]
name = "fedimint-mint-server"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-mint is a chaumian ecash mint module."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fedimint_mint_server"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
erased-serde = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-metrics = { version = "=0.4.3-rc.0", path = "../../fedimint-metrics" }
fedimint-mint-common = { version = "=0.4.3-rc.0", path = "../fedimint-mint-common" }
fedimint-server = { version = "=0.4.3-rc.0", path = "../../fedimint-server" }
futures = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
secp256k1-zkp = "0.9.2"
serde = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tbs = { package = "fedimint-tbs", version = "=0.4.3-rc.0", path = "../../crypto/tbs" }
threshold_crypto = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
test-log = { version = "0.2", features = [ "trace" ], default-features = false }
tokio = { version = "1.38.0", features = [ "full" ] }
