[package]
name = "fedimint-mint-server"
version = "0.2.0-rc2"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-mint is a chaumian ecash mint module."
license = "MIT"
repository = "https://github.com/fedimint/fedimint"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fedimint_mint_server"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.66"
assert_matches = "1.5.0"
async-trait = "0.1.73"
bincode = "1.3.1"
bitcoin_hashes = "0.11.0"
erased-serde = "0.3"
futures = "0.3"
itertools = "0.10.5"
fedimint-core = { version = "0.2.0-rc2", path = "../../fedimint-core" }
fedimint-mint-common = { version = "0.2.0-rc2", path = "../fedimint-mint-common" }
rand = "0.8"
secp256k1 = "0.24.2"
secp256k1-zkp = "0.7.0"
serde = { version = "1.0.149", features = [ "derive" ] }
strum = "0.24"
strum_macros = "0.24"
tbs = { package = "fedimint-tbs", version = "0.2.0-rc2", path = "../../crypto/tbs" }
thiserror = "1.0.39"
threshold_crypto = { workspace = true }
tracing ="0.1.37"
impl-tools = "0.8.0"
fedimint-server = { version = "0.2.0-rc2", path = "../../fedimint-server" }

[dev-dependencies]
fedimint-testing = { path = "../../fedimint-testing" }
rand = "0.8"
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
tokio = {version = "1.26.0", features = [ "full" ] }
test-log = { version = "0.2", features = [ "trace" ], default-features = false }
