[package]
authors = { workspace = true }
description = "fedimint-mint is a chaumian ecash mint module."
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-mint-server"
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_mint_server"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
erased-serde = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-metrics = { workspace = true }
fedimint-mint-common = { workspace = true }
fedimint-server-core = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tbs = { workspace = true }
threshold_crypto = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bitcoin = { workspace = true }
test-log = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
