[package]
authors = ["The Fedimint Developers"]
description = "fedimint-mint is a chaumian ecash mint module."
edition = "2021"
license = "MIT"
name = "fedimint-mintv2-server"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"
version = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_mintv2_server"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bitcoin = { workspace = true }
erased-serde = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-metrics = { workspace = true }
fedimint-mintv2-common = { workspace = true }
fedimint-server-core = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tbs = { workspace = true }
threshold_crypto = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
