[package]
authors = { workspace = true }
description = "fedimint-lnv2-tests contains integration tests for the lnv2 module"
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-lnv2-tests"
publish = false
version = { workspace = true }

[[bin]]
name = "lnv2-module-tests"
path = "bin/tests.rs"

[[bin]]
name = "lnv1-lnv2-swap-tests"
path = "bin/swap_tests.rs"

[[test]]
name = "fedimint_lnv2_tests"
path = "tests/tests.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bitcoin = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
devimint = { workspace = true }
fedimint-api-client = { workspace = true }
fedimint-client = { workspace = true }
fedimint-client-module = { workspace = true }
fedimint-core = { workspace = true }
fedimint-dummy-client = { workspace = true }
fedimint-dummy-common = { workspace = true }
fedimint-dummy-server = { workspace = true }
fedimint-ln-common = { workspace = true }
fedimint-lnv2-client = { workspace = true }
fedimint-lnv2-common = { workspace = true }
fedimint-lnv2-server = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-testing = { workspace = true }
hex-conservative = { workspace = true }
itertools = { workspace = true }
lightning-invoice = { workspace = true }
lnurl-rs = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
substring = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
