[package]
name = "fedimint-lightning"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = { workspace = true }
description = "fedimint-lightning handle the gateway's interaction with the lightning node"
license = { workspace = true }
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[lib]
name = "fedimint_lightning"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bitcoin = { workspace = true }
fedimint-bip39 = { workspace = true }
fedimint-core = { workspace = true }
fedimint-gateway-common = { workspace = true }
fedimint-ln-common = { workspace = true }
fedimint-logging = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
ldk-node = "0.4.3"
lightning = { workspace = true }
lightning-invoice = { workspace = true }
lockable = "0.1.1"
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic_lnd = { workspace = true }
tracing = { workspace = true, features = ["log"] }
