[package]
name = "minimint"
version = "0.1.0"
authors = ["elsirion <elsirion@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.42"
bincode = "1.3.1"
bitcoin = "0.27.0"
futures = "0.3.9"
hbbft = "0.1.1"
hex = "0.4.2"
itertools = "0.10.0"
minimint-api = { path = "../minimint-api" }
minimint-derive = { path = "../minimint-derive" }
minimint-mint = { path = "../modules/minimint-mint" }
minimint-wallet = { path = "../modules/minimint-wallet" }
rand = "0.6.5"
rayon = "1.5.0"
secp256k1-zkp = { git = "https://github.com/elsirion/rust-secp256k1-zkp", branch = "minimint", features = [ "global-context", "bitcoin_hashes" ] }
serde = { version = "1.0.118", features = [ "derive" ] }
serde_json = "1.0.61"
sha3 = "0.9.1"
sled = "0.34.6"
structopt = "0.3.21"
tbs = { path = "../crypto/tbs" }
thiserror = "1.0.23"
tide = "0.16.0"
tokio = { version = "1.0.1", features = ["full"] }
tokio-util = { version = "0.6.0", features = [ "compat" ] }
tracing ="0.1.22"
tracing-subscriber = "0.2.15"