[package]
name = "fedimint-meta-server"
version = "0.4.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-meta is a meta consensus fedimint module."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_meta_server"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = "0.1.80"
erased-serde = { workspace = true }
futures = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-meta-common = { version = "=0.4.0-alpha", path = "../fedimint-meta-common" }
rand = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tracing = { workspace = true }
