[package]
name = "fedimint-wallet"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-wallet is a n on-chain bitcoin wallet module. It uses a key-value store and is not a standard HD wallet."
license = "MIT"

[lib]
name = "fedimint_wallet"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
native = ["tokio", "fedimint-bitcoind"]
default = []

[dependencies]
anyhow = "1.0.65"
async-trait = "0.1"
bitcoin = { version = "0.29.1", features = [ "rand", "serde"] }
hex = "0.4.3"
fedimint-api = { path = "../../fedimint-api" }
fedimint-bitcoind = { path = "../../fedimint-bitcoind", optional = true }
miniscript = { version = "7.0.0", git = "https://github.com/rust-bitcoin/rust-miniscript/", rev = "2f1535e470c75fad85dbad8633986aae36a89a92", features = [ "compiler", "serde" ] }
rand = "0.8"
secp256k1 = { version = "0.24.0", features = [ "serde" ] }
serde = { version = "1.0.147", features = [ "derive" ] }
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["sync"], optional = true }
tracing ="0.1.37"
validator = { version = "0.16", features = ["derive"] }

[dev-dependencies]
test-log = { version = "0.2", features = [ "trace" ], default-features = false }
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
