[package]
name = "fedimint-wallet"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-wallet is a n on-chain bitcoin wallet module. It uses a key-value store and is not a standard HD wallet."
license = "MIT"

[lib]
name = "fedimint_wallet"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
native = ["tokio", "fedimint-bitcoind/bitcoincore-rpc"]
default = []

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1"
bitcoin = { version = "0.29.2", features = [ "rand", "serde"] }
erased-serde = "0.3"
fedimint-api = { path = "../../fedimint-api" }
fedimint-bitcoind = { path = "../../fedimint-bitcoind", features = [] }
futures = "0.3"
miniscript = { version = "7.0.0", git = "https://github.com/rust-bitcoin/rust-miniscript/", rev = "2f1535e470c75fad85dbad8633986aae36a89a92", features = [ "compiler", "serde" ] }
impl-tools = "0.6.1"
rand = "0.8"
secp256k1 = { version = "0.24.2", features = [ "serde" ] }
serde = { version = "1.0.149", features = [ "derive" ] }
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0.37"
tokio = { version = "1.25.0", features = ["sync"], optional = true }
tracing ="0.1.37"
url = "2.3.1"
validator = { version = "0.16", features = ["derive"] }

[dev-dependencies]
test-log = { version = "0.2", features = [ "trace" ], default-features = false }
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
