[package]
name = "fedimint-wallet"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-wallet is a n on-chain bitcoin wallet module. It uses a key-value store and is not a standard HD wallet."
license = "MIT"

[lib]
name = "fedimint_wallet"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
native = ["tokio", "bitcoincore-rpc"]
default = []

[dependencies]
anyhow = "1.0.65"
async-trait = "0.1"
bitcoin = { version = "0.28.1", features = [ "rand", "serde"] }
bitcoincore-rpc = {version = "0.15.0", optional = true}
hex = "0.4.3"
fedimint-api = { path = "../../fedimint-api" }
fedimint-derive = { path = "../../fedimint-derive" }
miniscript = { version = "7.0.0", features = [ "compiler", "use-serde" ] }
rand = "0.6.0"
secp256k1 = { version = "0.22.1", features = [ "serde" ] }
serde = { version = "1.0.145", features = [ "derive" ] }
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["sync"], optional = true }
tracing ="0.1.22"
validator = { version = "0.16", features = ["derive"] }

[dev-dependencies]
test-log = { version = "0.2", features = [ "trace" ], default-features = false }
tracing-subscriber = { version = "0.3.1", features = [ "env-filter" ] }
