[package]
name = "fedimint-aead"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "aead utilities on top of ring"
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_aead"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
argon2 = { workspace = true, features = ["password-hash", "alloc"] }
hex = { workspace = true }
rand = { workspace = true }
ring = { workspace = true }

[lints]
workspace = true
