[package]
name = "mint-client-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.28.1"
bitcoin_hashes = "0.10.0"
clap = { version = "3.1.18", features = ["derive"] }
lightning-invoice = "0.17.0"
mint-client = { path = "../client-lib" }
minimint-api = { path = "../../minimint-api" }
minimint-core = { path = "../../minimint-core" }
rand = "0.6.5"
reqwest = { version = "0.11.0", features = [ "json" ], default-features = false }
serde = { version = "1.0.118", features = [ "derive" ] }
sled = "0.34.6"
tokio = { version = "1.19.2", features = ["full"] }
tracing ="0.1.22"
tracing-subscriber = { version = "0.3.1", features = [ "env-filter" ] }
serde_json = "1.0.82"
