[package]
name = "fedimint-cli"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-cli is a command line interface wrapper for the client library."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "mint-rpc-client"
path = "src/bin/mint-rpc-client.rs"

[[bin]]
name = "fedimint-cli"
path = "src/main.rs"

[dependencies]
bitcoin = "0.29.1"
bitcoin_hashes = "0.11.0"
clap = { version = "4.0.17", features = ["derive"] }
lightning-invoice = "0.19.0"
mint-client = { path = "../client-lib" }
fedimint-api = { path = "../../fedimint-api" }
fedimint-core = { path = "../../fedimint-core" }
fedimint-rocksdb = { path = "../../fedimint-rocksdb" }
rand = "0.8"
serde = { version = "1.0.145", features = [ "derive" ] }
tokio = { version = "1.21.2", features = ["full"] }
tracing ="0.1.37"
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
serde_json = "1.0.86"
url = { version = "2.3.1", features = ["serde"] }

[build-dependencies]
fedimint-build = { path = "../../fedimint-build" }
