[package]
name = "fedimint-ln"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-ln is a lightning payment service module."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fedimint_ln"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1"
bincode = "1"
bitcoin_hashes = "0.11.0"
futures = "0.3.24"
itertools = "0.10.5"
lightning = "0.0.112"
lightning-invoice = { version = "0.20.0", features = [ "serde" ] }
fedimint-api = { path = "../../fedimint-api" }
secp256k1 = { version="0.24.1", default-features=false }
serde = {version = "1.0.147", features = [ "derive" ] }
serde_json = "1.0.86"
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0.37"
threshold_crypto = { git = "https://github.com/jkitman/threshold_crypto", branch = "upgrade-threshold-crypto-libs" }
tracing = "0.1.37"
rand = "0.8"
url = { version = "2.3.1", features = ["serde"] }
hbbft = { git = "https://github.com/jkitman/hbbft", branch = "upgrade-threshold-crypto-libs" }

[dev-dependencies]
tokio = {version = "1.21.2", features = [ "full" ] }
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
test-log = { version = "0.2", features = [ "trace" ], default-features = false }
fedimint-testing = { path = "../../fedimint-testing" }
