[package]
name = "fedimint-ln-tests"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-ln-tests contains integration tests for the lightning module"
license = "MIT"
publish = false

[[test]]
name = "fedimint_ln_tests"
path = "tests/tests.rs"

[dependencies]
anyhow = { workspace = true }
assert_matches = { workspace = true }
bitcoin_hashes = { workspace = true }
fedimint-client = { workspace = true }
fedimint-core = { workspace = true }
fedimint-dummy-client = { workspace = true }
fedimint-dummy-common = { workspace = true }
fedimint-dummy-server = { workspace = true }
fedimint-ln-client = { workspace = true }
fedimint-ln-common = { workspace = true }
fedimint-ln-server = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-testing = { workspace = true }
futures = { workspace = true }
lightning-invoice = { workspace = true }
rand = { workspace = true }
secp256k1 = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
threshold_crypto = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
