[package]
name = "fedimint-ln-tests"
version = "0.4.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-ln-tests contains integration tests for the lightning module"
license = "MIT"
publish = false

[[test]]
name = "fedimint_ln_tests"
path = "tests/tests.rs"

[dependencies]
anyhow = { workspace = true }
assert_matches = { workspace = true }
bitcoin_hashes = { workspace = true }
fedimint-bitcoind = { path = "../../fedimint-bitcoind" }
fedimint-dummy-common = { path = "../fedimint-dummy-common" }
fedimint-dummy-client = { path = "../fedimint-dummy-client" }
fedimint-dummy-server = { path = "../fedimint-dummy-server" }
fedimint-ln-common = { path = "../fedimint-ln-common" }
fedimint-ln-client = { path = "../fedimint-ln-client" }
fedimint-ln-server = { path = "../fedimint-ln-server" }
fedimint-testing = { path = "../../fedimint-testing" }
fedimint-client = { path = "../../fedimint-client" }
fedimint-core ={ path = "../../fedimint-core" }
fedimint-server = { path = "../../fedimint-server" }
fedimint-logging = { path = "../../fedimint-logging" }
futures = { workspace = true }
lightning-invoice = { version = "0.26.0", features = [ "serde" ] }
threshold_crypto = { workspace = true }
tokio = { version = "1.36.0", features = ["sync"] }
tracing = { workspace = true }
secp256k1 = { version="0.24.3", default-features=false }
serde_json = { workspace = true }
rand = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
