[package]
name = "fedimint-wallet-common"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-wallet is a n on-chain bitcoin wallet module. It uses a key-value store and is not a standard HD wallet."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_wallet_common"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
bitcoin = { workspace = true }
fedimint-core = { workspace = true }
hex = { workspace = true }
miniscript = { version = "10.0.0", features = [ "compiler", "serde" ] }
impl-tools = "0.10.0"
secp256k1 = { version = "0.27.0", features = [ "serde" ] }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
test-log = { version = "0.2", features = [ "trace" ], default-features = false }
