[package]
name = "fedimint-wallet-common"
version = "0.2.0-rc2"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-wallet is a n on-chain bitcoin wallet module. It uses a key-value store and is not a standard HD wallet."
license = "MIT"

[lib]
name = "fedimint_wallet_common"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.73"
bitcoin = { version = "0.29.2", features = [ "rand", "serde"] }
erased-serde = "0.3"
fedimint-core = { version = "0.2.0-rc2", path = "../../fedimint-core" }
futures = "0.3"
miniscript = { version = "9.0.2", features = [ "compiler", "serde" ] }
impl-tools = "0.8.0"
rand = "0.8"
secp256k1 = { version = "0.24.2", features = [ "serde" ] }
serde = { version = "1.0.149", features = [ "derive" ] }
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0.39"
tokio = { version = "1.26.0", features = ["sync"], optional = true }
tracing ="0.1.37"
url = "2.3.1"
validator = { version = "0.16", features = ["derive"] }

[dev-dependencies]
test-log = { version = "0.2", features = [ "trace" ], default-features = false }
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
