[package]
description = "recurringd is a service that allows Fedimint users to receive recurring payments"
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
name = "fedimint-recurringd"
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[[bin]]
name = "fedimint-recurringd"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
axum-auth = { workspace = true }
bitcoin = { workspace = true, features = ["serde"] }
clap = { workspace = true }
fedimint-api-client = { workspace = true }
fedimint-client = { workspace = true }
fedimint-connectors = { workspace = true }
fedimint-core = { workspace = true }
fedimint-derive-secret = { workspace = true }
fedimint-ln-client = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-mint-client = { workspace = true }
fedimint-rocksdb = { workspace = true }
futures = { workspace = true }
lightning-invoice = { workspace = true }
lnurl-rs = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
