[package]
name = "mint-client"
version = "0.1.0"
authors = ["elsirion <elsirion@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
bincode = "1.3.1"
bitcoin = "0.27.0"
bitcoin_hashes = "0.9.4"
futures = "0.3.9"
hex = "0.4.3"
lightning-invoice = "0.11.0"
miniscript = "6.0.0"
minimint = { path = "../minimint" }
minimint-api = { path = "../minimint-api" }
rand = "0.6.5"
reqwest = { version = "0.11.0", features = [ "json" ], default-features = false }
secp256k1-zkp = { git = "https://github.com/elsirion/rust-secp256k1-zkp", branch = "minimint", features = [ "serde", "bitcoin_hashes" ] }
serde = { version = "1.0.118", features = [ "derive" ] }
sha3 = "0.9.1"
sled = "0.34.6"
structopt = "0.3.21"
tbs = { path = "../crypto/tbs" }
thiserror = "1.0.23"
tokio = { version = "1.0.1", features = ["full"] }
tracing ="0.1.22"
tracing-subscriber = "0.2.15"
