[package]
name = "fedimint-hkdf"
version = "0.3.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "RFC5869 HKDF implementation on top of bitcoin_hashes"
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "hkdf"
path = "src/lib.rs"

[dependencies]
bitcoin_hashes = "0.11.0"
