[package]
name = "fedimint-hkdf"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "RFC5869 HKDF implementation on top of bitcoin_hashes"
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[lib]
name = "hkdf"
path = "src/lib.rs"

[dependencies]
bitcoin_hashes = { workspace = true }
