[package]
authors = { workspace = true }
description = "fedimint-testing provides a basic utils for testing fedimint components"
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-testing-core"
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_testing_core"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
bitcoin = { workspace = true }
fedimint-client = { workspace = true }
fedimint-client-module = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-rocksdb = { workspace = true }
fedimint-server = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
