[package]
name = "mint-client"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "mint-client provides a library for sending transactions to the federation."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "mint_client"
path = "src/lib.rs"


[dependencies]
anyhow = "1.0.65"
async-trait = "0.1.52"
base64 = "0.13.0"
bincode = "1.3.1"
bitcoin = "0.29.1"
bitcoin_hashes = "0.11.0"
futures = "0.3.24"
hex = "0.4.3"
lightning-invoice = "0.19.0"
lightning = "0.0.111"
miniscript = { version = "7.0.0", git = "https://github.com/rust-bitcoin/rust-miniscript/", rev = "2f1535e470c75fad85dbad8633986aae36a89a92" }
fedimint-core = { path = "../../fedimint-core" }
fedimint-api = { path = "../../fedimint-api" }
fedimint-derive = { path = "../../fedimint-derive" }
rand = "0.8"
reqwest = { version = "0.11.12", features = [ "json", "rustls-tls" ], default-features = false }
secp256k1-zkp = { version = "0.7.0", features = [ "serde", "bitcoin_hashes" ] }
serde = "1.0.145"
tbs = { path = "../../crypto/tbs" }
thiserror = "1.0.37"
tracing ="0.1.37"
jsonrpsee-types = "0.15.1"
jsonrpsee-core = { version = "0.15.1", features = [ "client" ] }
serde_json = "1.0.86"
url = { version = "2.3.1", features = ["serde"] }
threshold_crypto = { git = "https://github.com/jkitman/threshold_crypto", branch = "upgrade-threshold-crypto-libs" }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
jsonrpsee-ws-client = "0.15.1"

[target.'cfg(target_family = "wasm")'.dependencies]
js-sys = "0.3.59"
jsonrpsee-wasm-client = "0.15.1"

[dev-dependencies]
tokio = { version = "1.21.2", features = ["full"] }
test-log = { version = "0.2", features = [ "trace" ], default-features = false }
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
once_cell = "1.15.0"
