[package]
name = "mint-client"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "mint-client provides a library for sending transactions to the federation."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "mint_client"
path = "src/lib.rs"


[dependencies]
aead = { path = "../../crypto/aead" }
anyhow = "1.0.66"
async-trait = "0.1.64"
base64 = "0.20.0"
bincode = "1.3.1"
bitcoin = "0.29.2"
bitcoin_hashes = "0.11.0"
futures = "0.3.24"
hkdf = { path = "../../crypto/hkdf" }
lightning-invoice = "0.21.0"
lightning = "0.0.113"
miniscript = { version = "7.0.0", git = "https://github.com/rust-bitcoin/rust-miniscript/", rev = "2f1535e470c75fad85dbad8633986aae36a89a92" }
fedimint-core = { path = "../../fedimint-core" }
fedimint-derive-secret = { path = "../../crypto/derive-secret" }
fedimint-api = { path = "../../fedimint-api" }
fedimint-ln = { path = "../../modules/fedimint-ln" }
fedimint-mint = { path = "../../modules/fedimint-mint" }
fedimint-wallet = { path = "../../modules/fedimint-wallet", default-features = false }
itertools = "0.10.5"
rand = "0.8"
ring = "0.16.20"
reqwest = { version = "0.11.14", features = [ "json", "rustls-tls" ], default-features = false }
secp256k1 = "0.24.2"
secp256k1-zkp = { version = "0.7.0", features = [ "serde", "bitcoin_hashes" ] }
serde = "1.0.149"
strum = "0.24"
strum_macros = "0.24"
tbs = { path = "../../crypto/tbs" }
thiserror = "1.0.37"
tokio = { version = "1.25.0", features = ["sync"] }
tracing = "0.1.37"
jsonrpsee-types = "0.16.0"
jsonrpsee-core = { version = "0.16.2", features = [ "client" ] }
serde_json = "1.0.91"
url = { version = "2.3.1", features = ["serde"] }
threshold_crypto = { git = "https://github.com/jkitman/threshold_crypto", branch = "upgrade-threshold-crypto-libs" }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
jsonrpsee-ws-client = "0.16.2"

[target.'cfg(target_family = "wasm")'.dependencies]
jsonrpsee-wasm-client = "0.16.0"

[dev-dependencies]
fedimint-rocksdb = { path = "../../fedimint-rocksdb" }
tokio = { version = "1.25.0", features = ["full"] }
tempfile = "3.3.0"
test-log = { version = "0.2", features = [ "trace" ], default-features = false }
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
fedimint-testing = { path = "../../fedimint-testing" }
once_cell = "1.16.0"
