[package]
name = "mint-client"
version = "0.1.0"
authors = ["elsirion <elsirion@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "mint_client"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.58"
async-trait = "0.1.52"
base64 = "0.13.0"
bincode = "1.3.1"
bitcoin = "0.28.1"
bitcoin_hashes = "0.10.0"
futures = "0.3.9"
hex = "0.4.3"
lightning-invoice = "0.17.0"
lightning = "0.0.109"
miniscript = "7.0.0"
fedimint-core = { path = "../../fedimint-core" }
fedimint-api = { path = "../../fedimint-api" }
rand = "0.6.5"
reqwest = { version = "0.11.0", features = [ "json" ], default-features = false }
secp256k1-zkp = { version = "0.6.0", features = [ "serde", "bitcoin_hashes" ] }
serde = "1.0.118"
tbs = { path = "../../crypto/tbs" }
thiserror = "1.0.23"
tracing ="0.1.22"
jsonrpsee-types = "0.14.0"
jsonrpsee-core = "0.14.0"
serde_json = "1.0.82"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
jsonrpsee-ws-client = "0.14.0"

[target.'cfg(target_family = "wasm")'.dependencies]
js-sys = "0.3.59"
jsonrpsee-wasm-client = "0.14.0"

[dev-dependencies]
tokio = { version = "1.19.2", features = ["full"] }
test-log = { version = "0.2", features = [ "trace" ], default-features = false }
tracing-subscriber = { version = "0.3.1", features = [ "env-filter" ] }
once_cell = "1.13.0"
