on:
  schedule:
    - cron:  '30 5,17 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

name: Daily check

jobs:
  audit:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v6
      - name: Run cargo audit
        run: |
          nix flake update advisory-db || nix flake lock --update-input advisory-db
          nix build -L .#ci.cargoAudit

  fuzz:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v6
      - name: Quick fuzzing
        run: |
          env \
            PERFIT_ACCESS_TOKEN="${{ secrets.PERFIT_ACCESS_TOKEN }}" \
            nix run 'github:rustshop/perfit?rev=a2ea3bae86b0e70d2ebdbca1fd16a843b7f0a3bd#perfit' -- \
              run \
                --metric EOKLCdk0SRWnjmA0sLRFKQ \
                --metadata "commit=${LAST_COMMIT_SHA}" \
                -- \
              nix build -L .#ci.quickFuzz

  notifications:
    if: always() && github.repository == 'fedimint/fedimint'
    name: "Notifications"
    timeout-minutes: 1
    runs-on: [self-hosted, linux, x64]
    needs: [ audit, fuzz ]

    steps:
    - name: Discord notifications on failure
      # https://stackoverflow.com/a/74562058/134409
      if: ${{ always() && contains(needs.*.result, 'failure') }}
      # https://github.com/marketplace/actions/actions-status-discord
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        # current job is a success, but that's not what we're interested in
        status: failure
