on:
  schedule:
    - cron:  '30 5,17 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

name: Daily check

jobs:
  audit:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v6
      - name: Run cargo audit
        run: |
          nix flake update advisory-db || nix flake lock --update-input advisory-db
          nix build -L .#ci.cargoAudit

  check-packages-features:
    name: "Check package features"
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v6
      - uses: dpc/nix-installer-action@dpc/jj-vqymqvyntouw
      - uses: cachix/cachix-action@v16
        with:
          name: fedimint
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        continue-on-error: true
      - name: Check package features
        run: |
          nix develop -c just check-packages-features

  notifications:
    if: always() && github.repository == 'fedimint/fedimint'
    name: "Notifications"
    timeout-minutes: 1
    runs-on: [self-hosted, linux, x64]
    needs: [ audit, check-packages-features ]

    steps:
    - name: Discord notifications on failure
      # https://stackoverflow.com/a/74562058/134409
      if: ${{ always() && contains(needs.*.result, 'failure') }}
      # https://github.com/marketplace/actions/actions-status-discord
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        # current job is a success, but that's not what we're interested in
        status: failure
