on:
  schedule:
    - cron:  '30 5,17 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

name: Daily check

jobs:
  check-unused-dependencies:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Install native packages
        run: |
          sudo apt-get -y install mold

      - uses: Swatinem/rust-cache@v1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Installs cargo-udeps
        run: cargo install --force cargo-udeps

      - name: Run cargo udeps
        run: cargo udeps
