name: extra-docker-images

on:
  push:
    branches:
      - 'master'
      - 'releases/v*'
    tags:
      - 'v*'
jobs:
  docker:
    if: github.repository == 'fedimint/fedimint'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fedimint
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Docker meta for mutinynet-bitcoind
        id: meta-mutinynet-bitcoind
        uses: docker/metadata-action@v5
        with:
          images: |
            fedimint/mutinynet-bitcoind
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      - name: Build and push mutinynet-bitcoind
        uses: docker/build-push-action@v5
        with:
          file: docker/mutinynet-bitcoind-docker/Dockerfile
          push: true
          tags: ${{ steps.meta-mutinynet-bitcoind.outputs.tags }}
          labels: ${{ steps.meta-mutinynet-bitcoind.outputs.labels }}
      - name: Docker meta for xmpp-prosody-chat-server
        id: meta-xmpp-prosody
        uses: docker/metadata-action@v5
        with:
          images: |
            fedimint/xmpp-prosody-chat-server
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      - name: Build and push xmpp-prosody-chat-server
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:docker/full-tls-mutinynet/prosody"
          push: true
          tags: ${{ steps.meta-xmpp-prosody.outputs.tags }}
          labels: ${{ steps.meta-xmpp-prosody.outputs.labels }}
