on: [push, pull_request]

name: Markdown Link Check

# Grant the job read access to repo contents so ${{ secrets.GITHUB_TOKEN }} can be used
permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: [self-hosted, linux, x64]
    continue-on-error: true # can fail for external reasons, so don't be a blocker
    steps:
      - uses: actions/checkout@v4

      # Persist lychee cache, so we don't bother with checking same links all the time
      # Should also minimize number of flakes.
      - uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Check links
        # provide the GitHub token to lychee so API rateâ€limits are lifted to 5k/hour
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nix run nixpkgs#lychee -- \
            --verbose \
            --cache \
            --github-token $GITHUB_TOKEN \
            docs README.md

      - name: Prune errors from lychee cache
        if: always()
        run: |
          if [ -f .lycheecache ]; then
            # keep only 2xx and 3xx results, drop all 4xx/5xx
            grep -E ' [23][0-9]{2} ' .lycheecache > .lycheecache.pruned
            mv .lycheecache.pruned .lycheecache
          fi

      - name: Save lychee cache
        if: always()
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
