name: 'check reminders'

on:
  schedule:
    # Run every hour at the 10th minute
    - cron: '10 * * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: check reminders and notify
        uses: agrc/reminder-action@v1